##角色
INSERT INTO PUB_ROLES(ROLE_ID,ROLE_NAME,RELATION_ID,ROLE_GROUP_ID,DESCRIPTION) VALUES('CPORTALADMIN','云门户管理员','1',NULL,'云门户管理员');

##CPORTALADMIN功能权限
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('CPORTALADMIN', 'CPORTAL01000');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('CPORTALADMIN', 'CPORTAL01001');

##SUPERADMIN功能权限
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('SUPERADMIN', 'CPORTAL01000');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('SUPERADMIN', 'CPORTAL01001');