--模块
INSERT INTO PUB_MODULES (MODULE_CODE,MODULE_NAME,PARENT_MODULE_CODE,IS_LEAF_MODULE,APP_CODE,MODULE_PATH,MODULE_PATH_NAME,SEQ) VALUES ('CFORM10','Process Form Management','CFORM','1','-1','CFORM#CFORM10','CForm#Process Form Management',10);

--功能
INSERT INTO PUB_FUNCTIONS (FUNCTION_CODE,FUNCTION_NAME,MODULE_CODE,SEQ) VALUES ('CFORM1000','Form operation definition','CFORM10',1);
INSERT INTO PUB_FUNCTIONS (FUNCTION_CODE,FUNCTION_NAME,MODULE_CODE,SEQ) VALUES ('CFORM1002','Task URL definition','CFORM10',2);