--CFORMADMIN功能权限
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('CFORMADMIN', 'CFORM10000');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('CFORMADMIN', 'CFORM10002');

--SUPERADMIN功能权限
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('SUPERADMIN', 'CFORM10000');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('SUPERADMIN', 'CFORM10002');