##业务流程模型定义
CREATE TABLE WF_BUSINESS_PROCESS_DEF_MODEL
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_ID VARCHAR(32) NOT NULL,
	PROC_DEF_NAME VARCHAR(100) NOT NULL,
	PLUGIN_TYPE VARCHAR(32) NOT NULL,
	PROC_SPEC VARCHAR(32),
	CREATE_TIME CHAR(17) NOT NULL,
	MODIFY_TIME CHAR(17) NOT NULL,
	MODEL_CONTENT BLOB NOT NULL,
	EXTENSION_CONTENT BLOB,
	IS_HISTORY CHAR(1) NOT NULL,
	IS_VALID CHAR(1) DEFAULT '0' NOT NULL
);
##设置主键
ALTER TABLE WF_BUSINESS_PROCESS_DEF_MODEL
 ADD CONSTRAINT BUSIMODELPK PRIMARY KEY (ID);

##业务流程使用的模板类型
CREATE TABLE WF_BIZ_PROC_TEMPLATE_TYPE
(
	ID VARCHAR(32) NOT NULL,
	TEMPLATE_TYPE CHAR(1) NOT NULL,
	DESCRIPTION VARCHAR(100)
);
##设置主键
ALTER TABLE WF_BIZ_PROC_TEMPLATE_TYPE
 ADD CONSTRAINT BIZTEMPLATEPK PRIMARY KEY (ID);

##业务流程模型的环节的结构话存储
CREATE TABLE WF_BUSINESS_PROC_ACTIVITY_DEF
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	PROC_DEF_NAME VARCHAR(100) NOT NULL,
	ACT_DEF_ID VARCHAR(32) NOT NULL,
	ACT_DEF_NAME VARCHAR(100) NOT NULL
);
##设置主键
ALTER TABLE WF_BUSINESS_PROC_ACTIVITY_DEF
 ADD CONSTRAINT BIZPROCACTDEFPK PRIMARY KEY (ID);

##业务流程层次关系表
CREATE TABLE WF_BUSINESS_PROC_DEF_MODEL_REF
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	PROC_DEF_ID VARCHAR(32) NOT NULL,
	PROC_DEF_NAME VARCHAR(100) NOT NULL,
	HIGH_LEVEL_PROC_DEF_UNIQUE_ID VARCHAR(32),
	HIGH_LEVEL_PROC_DEF_ID VARCHAR(32),
	HIGH_LEVEL_PROC_DEF_NAME VARCHAR(100),
	HIGH_LEVEL_ACT_DEF_ID VARCHAR(32),
	HIGH_LEVEL_ACT_DEF_NAME VARCHAR(100),
	PROC_LEVEL INTEGER NOT NULL ,
	IS_LEAF CHAR(1) NOT NULL
);
##设置主键
ALTER TABLE WF_BUSINESS_PROC_DEF_MODEL_REF
 ADD CONSTRAINT BIZPROCMODELREFPK PRIMARY KEY (ID);
 
##业务流程定义视图
CREATE VIEW WF_BUSINESS_PROC_VIEW AS 
SELECT A.ID AS ACT_DEF_UNIQUE_ID, A.ACT_DEF_ID, A.ACT_DEF_NAME, P.ID AS PROC_DEF_UNIQUE_ID, P.PROC_DEF_ID, P.PROC_DEF_NAME, P.CREATE_TIME, P.IS_HISTORY
FROM WF_BUSINESS_PROC_ACTIVITY_DEF A RIGHT JOIN WF_BUSINESS_PROCESS_DEF_MODEL P
ON A.PROC_DEF_UNIQUE_ID = P.ID;