##信息流程模型定义
CREATE TABLE WF_INFO_PROCESS_DEF_MODEL
(
    ID VARCHAR(32) NOT NULL,
    PROC_DEF_ID VARCHAR (32) NOT NULL,
    PROC_DEF_NAME VARCHAR (100),
    PLUGIN_TYPE VARCHAR (32) NOT NULL,
    CREATE_TIME CHAR (17) NOT NULL,
    PROC_SPEC VARCHAR(32),
    MODEL_CONTENT BLOB NOT NULL ,
    EXTENSION_CONTENT BLOB ,
    IS_UTF8 CHAR (1),
    IS_HISTORY CHAR (1),
    PROCESS_TYPE VARCHAR(32),
    IS_FREEDOM CHAR(1) DEFAULT '0'
);
##主键
ALTER TABLE WF_INFO_PROCESS_DEF_MODEL  
  ADD CONSTRAINT  PRODEFMODPK  
  PRIMARY KEY (ID);

##信息流程所属单位定义
CREATE TABLE WF_INFO_PROC_DATA_REF_DEF(
ID  VARCHAR(32)  NOT NULL ,
PROC_DEF_UNIQUE_ID   VARCHAR(32) NOT NULL ,
ORGAN_ID   VARCHAR(32)  NOT NULL
);
##设置主键
ALTER TABLE WF_INFO_PROC_DATA_REF_DEF  
  ADD CONSTRAINT  PRODEFMODDATAREFPK  
  PRIMARY KEY (ID);

##信息流程定义页面按钮
CREATE TABLE WF_INFO_PROC_PAGE_BUTTON_DEF
( 
	ID VARCHAR (32)  NOT NULL ,
	DISPLAY_NAME VARCHAR (100)  NOT NULL ,
	DISPLAY_ORDER INTEGER DEFAULT 999 , 
	DESCRIPTION VARCHAR (100) ,
	PLUGIN_TYPE VARCHAR (32) NOT NULL ,
	NEED_SET_PROC_TYPE CHAR(1) DEFAULT '0',
	IS_VISIBLE CHAR(1) DEFAULT '1'
);
##设置主键
ALTER TABLE WF_INFO_PROC_PAGE_BUTTON_DEF  
  ADD CONSTRAINT  PRODEFPAGEBTNDEFPK  
  PRIMARY KEY (ID);

##信息流程插件定义
CREATE TABLE WF_INFO_PROC_PLUGIN_DEF
( 
	PLUGIN_NAME VARCHAR (100)  NOT NULL ,
	PLUGIN_TYPE VARCHAR (32)  NOT NULL ,
	PLUGIN_PATH  VARCHAR (200)  NOT NULL , 
	XML_PARSER VARCHAR (200) ,
	PARSER_TYPE CHAR (1) DEFAULT '0',
	ITEM_TYPE CHAR (1) DEFAULT '0' ,
	JS_PATH VARCHAR (200) ,
	JS_OBJECT VARCHAR (32) ,
	FILE_PARSER VARCHAR (200) 
);
##设置主键
ALTER TABLE WF_INFO_PROC_PLUGIN_DEF  
  ADD CONSTRAINT  PROCPLUGINDEFPK  
  PRIMARY KEY (PLUGIN_TYPE);

##新增流程定义权限控制表
CREATE TABLE WF_INFO_PROC_PERMISSION_CONFIG
(
    PERMISSION_CODE VARCHAR (32) NOT NULL ,
    PERMISSION_DESC VARCHAR (100) 
);
##设置主键
ALTER TABLE WF_INFO_PROC_PERMISSION_CONFIG
    ADD CONSTRAINT WFPERMISSIONPK 
    PRIMARY KEY (PERMISSION_CODE);

##参与者URL定义
CREATE TABLE WF_PART_URL_DEF
( 
	ID VARCHAR (32)  NOT NULL ,
	NAME VARCHAR (100) NOT NULL ,
	DISPLAY_ORDER INTEGER DEFAULT 999 , 
	IS_VISIBLE CHAR(1) DEFAULT '1',
	PART_URL VARCHAR (200) NOT NULL ,
	PART_RULE VARCHAR(255),
	PART_CATEGORY CHAR(1) DEFAULT '0' 
);
##设置主键
ALTER TABLE WF_PART_URL_DEF
    ADD CONSTRAINT WFPARTURLDEFPK 
    PRIMARY KEY (ID);
