##########################流程###########################
##流程定义
CREATE TABLE WF_PROCESS_DEF
(
   ID VARCHAR (32) NOT NULL ,
   PROC_DEF_ID VARCHAR (32) NOT NULL ,
   PROC_DEF_VERSION CHAR (17) NOT NULL ,
   NAME VARCHAR (100) NOT NULL ,
   AUTHOR VARCHAR (32) ,
   CREATE_TIME CHAR (17),
   PROCESS_TYPE VARCHAR (32),
   IS_SUB_PROC CHAR(1),
   DESCRIPTION VARCHAR(100),
   IS_FREEDOM CHAR(1) DEFAULT '0'
);

ALTER TABLE WF_PROCESS_DEF 
  ADD CONSTRAINT WFPROCESSDEF_PK 
  PRIMARY KEY (ID);

##流程限时定义
CREATE TABLE WF_PROCESS_LIMIT_DEF
(
   ID VARCHAR (32) NOT NULL ,
   PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   PROC_DEF_LIMIT DECIMAL (18,0) NOT NULL ,
   UNIT CHAR (1) NOT NULL ,
   LIMIT_AGENT_CLASS_NAME VARCHAR (255)
);
 ALTER TABLE WF_PROCESS_LIMIT_DEF
    ADD CONSTRAINT WFPROCESSLIMITD_PK 
    PRIMARY KEY (ID);

##流程警告定义
CREATE TABLE WF_PROCESS_WARN_DEF
(
   ID VARCHAR (32) NOT NULL ,
   PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   WARN DECIMAL (18,0) NOT NULL ,
   UNIT CHAR (1) NOT NULL ,
   FREQUENCY DECIMAL (18,0) ,
   FREQUENCY_UNIT CHAR (1) ,
   WARN_AGENT_CLASS_NAME VARCHAR (255) 
);
 ALTER TABLE WF_PROCESS_WARN_DEF
    ADD CONSTRAINT WFPROCESSWARNDE_PK 
    PRIMARY KEY (ID);
 
##流程预警消息定义
CREATE TABLE WF_PROC_WARN_MSG_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            PROC_WARN_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            MSG_TYPE VARCHAR (32) NOT NULL ,
            MSG_SEND_RULE VARCHAR (100) 
);
ALTER TABLE WF_PROC_WARN_MSG_DEF
    ADD CONSTRAINT WFPROCWARNMSGDE_PK 
    PRIMARY KEY (ID);
    
##流程监控者定义
CREATE TABLE WF_PROCESS_MONITOR_DEF
(
   PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   PARTICIPANT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL 
);

ALTER TABLE WF_PROCESS_MONITOR_DEF
  ADD CONSTRAINT WFPROCMONITORD_PK  
  PRIMARY KEY ( PROC_DEF_UNIQUE_ID , PARTICIPANT_DEF_UNIQUE_ID);

##人工发起流程的数据权限（新建任务权限）
CREATE TABLE WF_PROC_CREATE_MANUAL_DATA_REF
(
   PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   ORGAN_ID VARCHAR (32) NOT NULL 
);
 ALTER TABLE WF_PROC_CREATE_MANUAL_DATA_REF
    ADD CONSTRAINT WFPROCCREATEMAN_PK 
    PRIMARY KEY (PROC_DEF_UNIQUE_ID,ORGAN_ID);
    
############################环节#######################
##环节定义
CREATE TABLE WF_ACTIVITY_DEF
(
   ID VARCHAR (32) NOT NULL ,
   ACT_DEF_ID VARCHAR (32) NOT NULL ,
   PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   NAME VARCHAR (100) NOT NULL ,
   TYPE CHAR (2) NOT NULL ,
   JOIN_TYPE CHAR (1) NOT NULL ,
   SPLIT_TYPE CHAR (1) NOT NULL ,
   IS_START CHAR (1) NOT NULL ,
   IS_END CHAR (1) NOT NULL ,
   FORK_ACT_DEF_UNIQUE_ID VARCHAR (32) ,
   IS_COUNTER_SIGNATURE CHAR (1) ,
   IS_ACT_INSTANCE_PER_PARTY CHAR (1) ,
   EXCUTION_TYPE CHAR (1) ,
   SUB_PROC_DEF_ID VARCHAR (32),
   DESCRIPTION VARCHAR(100), 
   COMPUTING_TIME CHAR(1) NOT NULL
);

ALTER TABLE WF_ACTIVITY_DEF 
  ADD CONSTRAINT WFACTIVITYDEF_PK 
  PRIMARY KEY (ID);
 
  ##环节限时定义
CREATE TABLE WF_ACTIVITY_LIMIT_DEF
(
  ID VARCHAR (32) NOT NULL ,
  ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
  ACT_DEF_LIMIT DECIMAL (18,0) NOT NULL ,
  UNIT CHAR (1) NOT NULL ,
  LIMIT_AGENT_CLASS_NAME VARCHAR (255) 
);
 ALTER TABLE WF_ACTIVITY_LIMIT_DEF
    ADD CONSTRAINT WFACTLIMITDEF_PK 
    PRIMARY KEY (ID);
    
##环节警告定义
CREATE TABLE WF_ACTIVITY_WARN_DEF
(
  ID VARCHAR (32) NOT NULL ,
  ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
  WARN DECIMAL (18,0) NOT NULL ,
  UNIT CHAR (1) NOT NULL ,
  FREQUENCY DECIMAL (18,0) ,
  FREQUENCY_UNIT CHAR (1) ,
  WARN_AGENT_CLASS_NAME VARCHAR (255)
);
 ALTER TABLE WF_ACTIVITY_WARN_DEF
    ADD CONSTRAINT WFACTIVITYWARND_PK 
    PRIMARY KEY (ID);
  
##环节预警消息定义
CREATE TABLE WF_ACT_WARN_MSG_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_WARN_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            MSG_TYPE VARCHAR (32) NOT NULL ,
            MSG_SEND_RULE VARCHAR (100) 
);
 ALTER TABLE WF_ACT_WARN_MSG_DEF
    ADD CONSTRAINT WFACTWARNMSGDEF_PK 
    PRIMARY KEY (ID);
    
##环节定义关联业务处理url
CREATE TABLE WF_ACT_DEF_SOURCE_URL_REF
(
   ID VARCHAR (32) NOT NULL ,
   ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   TYPE CHAR (1) NOT NULL ,
   URL VARCHAR (500) NOT NULL,
   PARAMETER_TYPE CHAR(1) NOT NULL,
   APP_CODE VARCHAR(30)
);
 ALTER TABLE WF_ACT_DEF_SOURCE_URL_REF
    ADD CONSTRAINT WFACTDEFSOURCEU_PK 
    PRIMARY KEY (ID);

##环节对应URL动态参数定义
CREATE TABLE WF_TASK_URL_DYNAMIC_PARAM_DEF
(
	ID VARCHAR (32) NOT NULL ,
	ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
	TASK_TYPE CHAR(1) NOT NULL,
	PARAMETER_KEY VARCHAR (32) NOT NULL ,
	PARAMETER_VALUE VARCHAR (32) NOT NULL
);
 ALTER TABLE WF_TASK_URL_DYNAMIC_PARAM_DEF
    ADD CONSTRAINT WFACTTASKDYNPARMPK
    PRIMARY KEY (ID);
    
##环节关联参与者定义
CREATE TABLE WF_ACT_PART_REF_DEF
(
   ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   PARTICIPANT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL 
);

ALTER TABLE WF_ACT_PART_REF_DEF
    ADD CONSTRAINT WFACTPARTREFDEF_PK 
    PRIMARY KEY (ACT_DEF_UNIQUE_ID,PARTICIPANT_DEF_UNIQUE_ID);
   
##############################参与者##########################
##参与者定义
CREATE TABLE WF_PARTICIPANT_DEF
(
   ID VARCHAR (32) NOT NULL ,
   PART_DEF_ID VARCHAR (32) NOT NULL ,
   PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   NAME VARCHAR (100) ,
   ITEM_NAME VARCHAR (100) ,
   ITEM_VALUE VARCHAR (255) ,
   ITEM_TYPE VARCHAR (100) NOT NULL 
);
 ALTER TABLE WF_PARTICIPANT_DEF
    ADD CONSTRAINT WFPARTICIPANTDE_PK 
    PRIMARY KEY (ID);
    
##############################迁移线##########################
##迁移线定义
CREATE TABLE WF_TRANSITION_DEF
(
   ID VARCHAR (32) NOT NULL ,
   TRANS_DEF_ID VARCHAR (32) NOT NULL ,
   PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   NAME VARCHAR (100) ,
   TRANS_CONDITION VARCHAR (1024) ,
   FROM_ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   TO_ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
   TYPE CHAR (1) 
);
 ALTER TABLE WF_TRANSITION_DEF
    ADD CONSTRAINT WFTRANSITIONDEF_PK 
    PRIMARY KEY (ID);
  
############################任务分配规则#####################
##任务分配规则类型定义
CREATE TABLE WF_ASSIGN_RULE_TYPE_DEF 
(
	ID VARCHAR(32) NOT NULL,
	ACT_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	RULE_TYPE CHAR(1) NOT NULL
);
ALTER TABLE WF_ASSIGN_RULE_TYPE_DEF 
	ADD CONSTRAINT ASINRUTYPEDEFPK  
    PRIMARY KEY(ID);

##任务分配轮转规则定义
CREATE TABLE WF_ASSIGN_RULE_IN_TURN_DEF 
(
	ID VARCHAR(32) NOT NULL,
	ASSIGN_RULE_TYPE_DEF_ID VARCHAR(32) NOT NULL,
	RULE_CONTENT VARCHAR(2048) NOT NULL
);
ALTER TABLE WF_ASSIGN_RULE_IN_TURN_DEF 
	ADD CONSTRAINT ASINRUINTURNDEFPK  
    PRIMARY KEY(ID);

##########################相关数据###########################
##相关数据定义
 CREATE TABLE WF_DATA_FIELD_DEF 
( 
 	ID VARCHAR(32) NOT NULL, 
 	DATA_FIELD_DEF_ID VARCHAR(32) NOT NULL, 
 	DATA_TYPE VARCHAR(32) NOT NULL, 
 	IS_PERSISTENCE CHAR (1),
 	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL 
);
ALTER TABLE WF_DATA_FIELD_DEF 
    ADD CONSTRAINT DATAFLDDEFPK 
PRIMARY KEY(ID);

##主流程与子流程相关数据映射定义
CREATE TABLE WF_DATA_FIELD_MAPPING_DEF
(
    ID VARCHAR (32) NOT NULL ,
    PARENT_PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
    SUB_PROC_DEF_ID VARCHAR (32) NOT NULL ,
    FROM_DATA_FIELD_DEF_ID VARCHAR (32) NOT NULL ,
    TO_DATA_FIELD_DEF_ID VARCHAR (32) NOT NULL ,
    MAPPING_WAY CHAR (1) NOT NULL 
);

ALTER TABLE WF_DATA_FIELD_MAPPING_DEF
    ADD CONSTRAINT DATAFIELDMAPPIN_PK 
    PRIMARY KEY (ID);
##环节业务数据主键对应相关数据定义
CREATE TABLE WF_ACT_PK_DATA_FIELD_DEF 
( 
 	ID VARCHAR(32) NOT NULL, 
 	SOURCE_PK_ID VARCHAR(32) NOT NULL, 
	DATA_FIELD_DEF_UNIQUE_ID VARCHAR(32) NOT NULL, 
 	ACT_DEF_UNIQUE_ID VARCHAR(32) NOT NULL, 
 	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL 
);
ALTER TABLE WF_ACT_PK_DATA_FIELD_DEF
    ADD CONSTRAINT DATAFLDEDFPK
    PRIMARY KEY(ID);

#######################图形信息#########################
##图形信息
CREATE TABLE WF_ACT_DEF_GRAPH 
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	ACT_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	X_OFFSET DECIMAL (18,0) NOT NULL,
	Y_OFFSET DECIMAL (18,0) NOT NULL
);
ALTER TABLE WF_ACT_DEF_GRAPH 
	ADD CONSTRAINT ACTDEFGRAPHPK  
    PRIMARY KEY(ID);

##流程起始点定义
CREATE TABLE WF_START_DEF_GRAPH 
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	ACT_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	X_OFFSET DECIMAL (18,0) NOT NULL,
	Y_OFFSET DECIMAL (18,0) NOT NULL
);
ALTER TABLE WF_START_DEF_GRAPH 
	ADD CONSTRAINT STARTDEFGRAPHPK 
    PRIMARY KEY(ID);

##流程结束点定义
CREATE TABLE WF_END_DEF_GRAPH 
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	ACT_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	X_OFFSET DECIMAL (18,0) NOT NULL,
	Y_OFFSET DECIMAL (18,0) NOT NULL
);
ALTER TABLE WF_END_DEF_GRAPH 
	ADD CONSTRAINT ENDDEFGRAPHPK  
    PRIMARY KEY(ID);


    
##################外部活动环节外键#####################
 ##流程定义与业务表关联
CREATE TABLE WF_PROC_DEF_SOURCE_REF
(
    ID VARCHAR (32) NOT NULL,
    PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL,
    SOURCE_TABLE VARCHAR (128) NOT NULL,
    SOURCE_PK VARCHAR (128) NOT NULL
);
##任务标题
CREATE TABLE WF_PROC_DEF_SOURCE_SUBJECT_REF
(
    ID VARCHAR (32) NOT NULL,
    SOURCE_COLUMN VARCHAR (128) NOT NULL,
    SOURCE_COLUMN_ALIAS VARCHAR (100) NOT NULL,
    PROC_DEF_SOURCE_REF_ID VARCHAR (32) NOT NULL
);
CREATE TABLE WF_ACT_DEF_JSP_BUTTON(
	ID  VARCHAR(32) NOT NULL,
	ACT_DEF_UNIQUE_ID  VARCHAR(32) NOT NULL,
	BUTTON_ID  VARCHAR(32) NOT NULL,
    BUTTON_NAME  VARCHAR(32),
	BUTTON_FUN_NAME  VARCHAR(32),
	TASK_TYPE CHAR(1) DEFAULT '1',
	BUTTON_ORDER integer,
	DEVICE_TYPE CHAR(1) DEFAULT '0'
);
CREATE TABLE WF_ACT_DEF_JSP_FIELD(
	ID  VARCHAR(32) NOT NULL,
	ACT_DEF_UNIQUE_ID  VARCHAR(32) NOT NULL,
	FIELD_ID  VARCHAR(32) NOT NULL,
    FIELD_NAME  VARCHAR(32),
	IS_HIDDEN  CHAR(1),
	IS_READ_ONLY  CHAR(1),
	IS_NOT_NULL CHAR (1),
	FIELD_TYPE VARCHAR (32),
	DEVICE_TYPE CHAR(1) DEFAULT '0'
);
ALTER TABLE WF_ACT_DEF_JSP_FIELD
    ADD CONSTRAINT ACTDEFJSPFLDPK
PRIMARY KEY (ID);
ALTER TABLE WF_PROC_DEF_SOURCE_REF
    ADD CONSTRAINT PRODEFSOCREFPK
PRIMARY KEY (ID);
ALTER TABLE WF_PROC_DEF_SOURCE_SUBJECT_REF
    ADD CONSTRAINT PRODEFSOCSBJREFPK
PRIMARY KEY (ID);
ALTER TABLE WF_ACT_DEF_JSP_BUTTON
    ADD CONSTRAINT ACTDEFJSPBTNPK
PRIMARY KEY (ID);

############################任务标题定义###########################

##系统全局层次的任务列表业务信息定义
CREATE TABLE WF_SYS_SUBJECT_DEF
(
            ID VARCHAR (32) NOT NULL ,
            SUBJECT_KEY VARCHAR (32) NOT NULL ,
            SUBJECT_ALIAS VARCHAR (100) NOT NULL,
             SUBJECT_ORDER DECIMAL(18,0),
            SUBJECT_WIDTH VARCHAR(32),
            IS_QUERY_CONDITION CHAR(1),
            SUBJECT_CATEGORY CHAR(1) DEFAULT '0',
            TASK_TYPE CHAR(1)
);
ALTER TABLE WF_SYS_SUBJECT_DEF
    ADD CONSTRAINT SYSSUBJECTDEF_PK 
    PRIMARY KEY (ID);

##流程类型层次的任务列表业务信息定义
CREATE TABLE WF_TYPE_SUBJECT_DEF(
  ID  VARCHAR(32)  NOT NULL,
  PROCESS_TYPE  VARCHAR(32) ,
  SUBJECT_KEY VARCHAR(32) ,
  SUBJECT_ALIAS VARCHAR(100),
  SUBJECT_ORDER DECIMAL(18,0),
  SUBJECT_WIDTH VARCHAR(32),
  IS_QUERY_CONDITION CHAR(1),
  SUBJECT_CATEGORY CHAR(1) DEFAULT '0',
  TASK_TYPE CHAR(1)
);
ALTER TABLE WF_TYPE_SUBJECT_DEF
    ADD CONSTRAINT WFTYPESUBJECT_PK 
    PRIMARY KEY (ID);

##流程定义层次的任务列表业务信息定义
CREATE TABLE WF_PROC_SUBJECT_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SUBJECT_KEY VARCHAR (32) NOT NULL ,
            SUBJECT_ALIAS VARCHAR (100) NOT NULL,
            SUBJECT_ORDER DECIMAL(18,0),
            SUBJECT_WIDTH VARCHAR(32),
            IS_QUERY_CONDITION CHAR(1),
            SUBJECT_CATEGORY CHAR(1) DEFAULT '0',
            TASK_TYPE CHAR(1)
);
ALTER TABLE WF_PROC_SUBJECT_DEF
    ADD CONSTRAINT PROCSUBJECTDEF_PK 
    PRIMARY KEY (ID);

############################任务标题来源类型定义###########################
##流程类型层次的任务列表业务信息来源类型定义
CREATE TABLE WF_TYPE_SUBJECT_SC_TYPE_DEF(
  ID  VARCHAR(32)  NOT NULL,
  PROCESS_TYPE  VARCHAR(32) ,
  SOURCE_TYPE CHAR(1) 
);
ALTER TABLE WF_TYPE_SUBJECT_SC_TYPE_DEF
    ADD CONSTRAINT TYPESUBJSCTYPEPK 
    PRIMARY KEY (ID);

##流程定义层次的任务列表业务信息来源类型定义
CREATE TABLE WF_PROC_SUBJECT_SC_TYPE_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SOURCE_TYPE CHAR (1) NOT NULL 
);
ALTER TABLE WF_PROC_SUBJECT_SC_TYPE_DEF
    ADD CONSTRAINT PROCSUBJSCTYPE_PK 
    PRIMARY KEY (ID);

############################任务标题关联定义(业务表)###########################
##流程类型层次的任务列表业务信息来源关联业务表定义
CREATE TABLE WF_TYPE_SUBJECT_TABLE_DEF(
  ID  VARCHAR(32)  NOT NULL,
  PROCESS_TYPE  VARCHAR(32) ,
  TABLE_NAME VARCHAR(32),
  PRIMARY_KEY VARCHAR(32)
);
ALTER TABLE WF_TYPE_SUBJECT_TABLE_DEF
    ADD CONSTRAINT TYPESUBJTABLEPK 
    PRIMARY KEY (ID);

##流程类型层次的任务列表业务信息来源关联业务表字段定义
CREATE TABLE WF_TYPE_SUBJECT_COLUMN_DEF(
  ID  VARCHAR(32)  NOT NULL,
  TYPE_SUBJECT_DEF_ID  VARCHAR(32) ,
  COLUMN_NAME VARCHAR(32) 
);
ALTER TABLE WF_TYPE_SUBJECT_COLUMN_DEF
    ADD CONSTRAINT TYPESUBJCOLUMNPK 
    PRIMARY KEY (ID);

##流程定义层次的任务列表业务信息来源关联业务表定义
CREATE TABLE WF_PROC_SUBJECT_TABLE_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            TABLE_NAME VARCHAR (30) NOT NULL ,
            PRIMARY_KEY VARCHAR (32) NOT NULL 
);

ALTER TABLE WF_PROC_SUBJECT_TABLE_DEF
    ADD CONSTRAINT PROCSUBJECTTABL_PK 
    PRIMARY KEY (ID);

##流程定义层次的任务列表业务信息来源关联业务表字段定义
CREATE TABLE WF_PROC_SUBJECT_COLUMN_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_SUBJECT_DEF_ID VARCHAR (32) NOT NULL ,
            COLUMN_NAME VARCHAR (32) NOT NULL 
);
ALTER TABLE WF_PROC_SUBJECT_COLUMN_DEF
    ADD CONSTRAINT PROCSUBJECTCOLU_PK 
    PRIMARY KEY (ID);
    
############################任务标题查询条件定义###########################
##系统全局层次任务列表业务信息查询条件定义
CREATE TABLE WF_SYS_SUBJECT_QUERY_DEF
(
            ID VARCHAR (32) NOT NULL ,
            SUBJECT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SUBJECT_FIELD_TYPE CHAR (1) NOT NULL ,
            SUBJECT_ORDER DECIMAL (18,0) NOT NULL 
);
ALTER TABLE WF_SYS_SUBJECT_QUERY_DEF
    ADD CONSTRAINT SYSSUBJECTQUERY_PK 
    PRIMARY KEY (ID);

##流程类型层次任务列表业务信息查询条件定义
CREATE TABLE WF_TYPE_SUBJECT_QUERY_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROCESS_TYPE VARCHAR (32) NOT NULL ,
            SUBJECT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SUBJECT_FIELD_TYPE CHAR (1) NOT NULL ,
            SUBJECT_ORDER DECIMAL (18,0) NOT NULL 
);
 ALTER TABLE WF_TYPE_SUBJECT_QUERY_DEF
    ADD CONSTRAINT TYPESUBJECTQUER_PK 
    PRIMARY KEY (ID);

##流程定义层次任务列表业务信息查询条件定义
CREATE TABLE WF_PROC_SUBJECT_QUERY_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SUBJECT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SUBJECT_FIELD_TYPE CHAR (1) NOT NULL ,
            SUBJECT_ORDER DECIMAL (18,0) NOT NULL  
);
 ALTER TABLE WF_PROC_SUBJECT_QUERY_DEF
    ADD CONSTRAINT PROCSUBJECTQUER_PK 
    PRIMARY KEY (ID);
    
##流程扩展属性定义
CREATE TABLE WF_PROC_EXT_ATTR_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ATTR_KEY VARCHAR (32) NOT NULL ,
            ATTR_VALUE VARCHAR (100) NOT NULL 
);
ALTER TABLE WF_PROC_EXT_ATTR_DEF
    ADD CONSTRAINT WFPROCEXTATTRDE_PK 
    PRIMARY KEY (ID);

##环节组扩展属性定义
CREATE TABLE WF_ACT_SET_EXT_ATTR_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_SET_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ATTR_KEY VARCHAR (32) NOT NULL ,
            ATTR_VALUE VARCHAR (100) NOT NULL 
);
 ALTER TABLE WF_ACT_SET_EXT_ATTR_DEF
    ADD CONSTRAINT WFACTSETEXTATTR_PK 
    PRIMARY KEY (ID);

##环节扩展属性定义
CREATE TABLE WF_ACT_EXT_ATTR_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ATTR_KEY VARCHAR (32) NOT NULL ,
            ATTR_VALUE VARCHAR (100) NOT NULL 
);
 ALTER TABLE WF_ACT_EXT_ATTR_DEF
    ADD CONSTRAINT WFACTEXTATTRDEF_PK 
    PRIMARY KEY (ID);
 
 ##环节组定义
CREATE TABLE WF_ACT_SET_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_SET_DEF_ID VARCHAR (32) NOT NULL ,
            ACT_SET_DEF_NAME VARCHAR (100) NOT NULL ,
            START_ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            END_ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL 
);
ALTER TABLE WF_ACT_SET_DEF
    ADD CONSTRAINT ACTSETDEF_PK 
    PRIMARY KEY (ID);

##环节关联环节组定义
CREATE TABLE WF_ACT_SET_REF_DEF
(
            ID VARCHAR (32) NOT NULL ,
	    PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_SET_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_DEF_ID VARCHAR (32) NOT NULL ,
            ACT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL 
);
 ALTER TABLE WF_ACT_SET_REF_DEF
    ADD CONSTRAINT ACTSETREFDEF_PK 
    PRIMARY KEY (ID);
    
##环节组限时定义
CREATE TABLE WF_ACT_SET_LIMIT_DEF
(
            ID VARCHAR (32) NOT NULL ,
	        PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_SET_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            LIMIT_TIME DECIMAL (18,0) NOT NULL ,
            LIMIT_UNIT CHAR (1) NOT NULL 
);

ALTER TABLE WF_ACT_SET_LIMIT_DEF
    ADD CONSTRAINT ACTSETLIMITDEF_PK 
    PRIMARY KEY (ID);

##环节组预警定义
CREATE TABLE WF_ACT_SET_WARN_DEF
(
            ID VARCHAR (32) NOT NULL ,
	        PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_SET_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            WARN_TIME DECIMAL (18,0) NOT NULL ,
            WARN_UNIT CHAR (1) NOT NULL 
);
 ALTER TABLE WF_ACT_SET_WARN_DEF
    ADD CONSTRAINT ACTSETWARNDEF_PK 
    PRIMARY KEY (ID);
    
##环节组预警消息定义
CREATE TABLE WF_ACT_SET_WARN_MSG_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_SET_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            ACT_SET_WARN_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            MSG_TYPE VARCHAR (32) NOT NULL ,
            MSG_SEND_RULE VARCHAR (100) 
);
 ALTER TABLE WF_ACT_SET_WARN_MSG_DEF
    ADD CONSTRAINT WFACTSETWARNMSG_PK 
    PRIMARY KEY (ID);

##20101021增加流程定义通用帮助表
CREATE TABLE WF_PROC_SUBJ_QUERY_HELP_DEF
(
     ID VARCHAR (32) NOT NULL ,
     PROC_DEF_UNIQUE_ID VARCHAR (32) ,
     SUBJECT_QUERY_DEF_UNIQUE_ID VARCHAR (32) ,
     DIALOG_URL VARCHAR (200) ,
     DIALOG_WIDTH CHAR (10) ,
     DIALOG_HEIGHT CHAR (10) ,
     CONDITION_USE_WAY CHAR (1) ,
     KEY_RETURN_INDEX DECIMAL(18,0),
     ALIAS_RETURN_INDEX DECIMAL(18,0)
);
##主键
ALTER TABLE WF_PROC_SUBJ_QUERY_HELP_DEF
    ADD CONSTRAINT WFPROCSUBJQUERYHPK 
    PRIMARY KEY (ID);
    
##20101021增加流程类型通用帮助定义
CREATE TABLE WF_TYPE_SUBJ_QUERY_HELP_DEF
(
        ID VARCHAR (32) NOT NULL,
        PROCESS_TYPE VARCHAR (32) NOT NULL,
        SUBJECT_QUERY_DEF_UNIQUE_ID VARCHAR (32) NOT NULL,
        DIALOG_URL VARCHAR (200) NOT NULL,
        DIALOG_WIDTH CHAR (10) NOT NULL,
        DIALOG_HEIGHT CHAR (10) NOT NULL,
        CONDITION_USE_WAY CHAR (1) NOT NULL,
         KEY_RETURN_INDEX DECIMAL(18,0),
    	 ALIAS_RETURN_INDEX DECIMAL(18,0)
);
##主键
ALTER TABLE WF_TYPE_SUBJ_QUERY_HELP_DEF
    ADD CONSTRAINT WFTYPSUBJQUERYH_PK 
PRIMARY KEY (ID);

##20101021增加系统全局通用帮助定义
CREATE TABLE WF_SYS_SUBJ_QUERY_HELP_DEF
(
            ID VARCHAR (32) NOT NULL ,
            SUBJECT_QUERY_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            DIALOG_URL VARCHAR (200) NOT NULL ,
            DIALOG_WIDTH CHAR (10) NOT NULL ,
            DIALOG_HEIGHT CHAR (10) NOT NULL ,
            CONDITION_USE_WAY CHAR (1) NOT NULL ,
             KEY_RETURN_INDEX DECIMAL(18,0),
     		ALIAS_RETURN_INDEX DECIMAL(18,0)
);
##主键
ALTER TABLE WF_SYS_SUBJ_QUERY_HELP_DEF
    ADD CONSTRAINT WFSYSSUBJQUERYH_PK 
    PRIMARY KEY (ID);
    
##20101022增加属性配置文件
CREATE TABLE WF_PROPERTY_CONFIG
(
            ID VARCHAR (32) NOT NULL ,
            PROPERTY_KEY VARCHAR (32) NOT NULL ,
            PROPERTY_VALUE VARCHAR (100) NOT NULL ,
            PARSER_TYPE CHAR(1) DEFAULT '0' NOT NULL ,
            PROPERTY_DESCRIPTION VARCHAR (100) 
);
ALTER TABLE WF_PROPERTY_CONFIG
    ADD CONSTRAINT WFPROPERTYCONFI_PK 
    PRIMARY KEY (ID);

##20101105
##系统全局下拉框定义
CREATE TABLE WF_SYS_SUBJ_QUERY_SELECT_DEF
(
            ID VARCHAR (32) NOT NULL ,
            SUBJECT_QUERY_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            OPTION_VALUE VARCHAR (32) NOT NULL ,
            OPTION_TEXT VARCHAR (100) NOT NULL 
);
ALTER TABLE WF_SYS_SUBJ_QUERY_SELECT_DEF
    ADD CONSTRAINT WFSYSSUBJQUERYS_PK 
    PRIMARY KEY (ID);
##流程类型下拉框定义
CREATE TABLE WF_TYPE_SUBJ_QUERY_SELECT_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROCESS_TYPE VARCHAR (32) NOT NULL ,
            SUBJECT_QUERY_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            OPTION_VALUE VARCHAR (32) NOT NULL ,
            OPTION_TEXT VARCHAR (100) NOT NULL 
);
 ALTER TABLE WF_TYPE_SUBJ_QUERY_SELECT_DEF
    ADD CONSTRAINT WFTYPESUBJQUERY_PK 
    PRIMARY KEY (ID);

##流程定义层次任务列表标题查询下拉框定义
CREATE TABLE WF_PROC_SUBJ_QUERY_SELECT_DEF
(
        ID VARCHAR (32) NOT NULL,
        PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL,
        SUBJECT_QUERY_DEF_UNIQUE_ID VARCHAR (32) NOT NULL,
        OPTION_VALUE VARCHAR (32),
        OPTION_TEXT VARCHAR (100)
);
ALTER TABLE WF_PROC_SUBJ_QUERY_SELECT_DEF
    ADD CONSTRAINT WFPROCSUBJQUERYSPK
PRIMARY KEY (ID);
    
ALTER TABLE WF_SYS_SUBJ_QUERY_SELECT_DEF
    ADD CONSTRAINT WFSYSSUBJECTQ_FK1 FOREIGN KEY (SUBJECT_QUERY_DEF_UNIQUE_ID)
    REFERENCES WF_SYS_SUBJECT_QUERY_DEF (ID);
ALTER TABLE WF_TYPE_SUBJ_QUERY_SELECT_DEF
    ADD CONSTRAINT WFTYPESUBJECTQ_FK1 FOREIGN KEY (SUBJECT_QUERY_DEF_UNIQUE_ID)
    REFERENCES WF_TYPE_SUBJECT_QUERY_DEF (ID);
ALTER TABLE WF_PROC_SUBJ_QUERY_SELECT_DEF
    ADD CONSTRAINT WFPROCSUBJECTQ_FK1 FOREIGN KEY (SUBJECT_QUERY_DEF_UNIQUE_ID)
    REFERENCES WF_PROC_SUBJECT_QUERY_DEF (ID);
    
    ##默认任务标题定义
CREATE TABLE WF_DEFAULT_SUBJECT_DEF
(
            ID VARCHAR (32) NOT NULL ,
            SUBJECT_KEY VARCHAR (32) NOT NULL ,
            SUBJECT_ALIAS VARCHAR (100) NOT NULL,
            SUBJECT_ORDER DECIMAL(18,0),
            SUBJECT_WIDTH VARCHAR(32),
            IS_QUERY_CONDITION CHAR(1),
            SUBJECT_CATEGORY CHAR(1),
            TASK_TYPE CHAR(1)
);
ALTER TABLE WF_DEFAULT_SUBJECT_DEF
    ADD CONSTRAINT DEFAULTSUBJDEFPK 
PRIMARY KEY (ID);
##默认任务标题查询条件定义
CREATE TABLE WF_DEFAULT_SUBJECT_QUERY_DEF
(
            ID VARCHAR (32) NOT NULL ,
            SUBJECT_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SUBJECT_FIELD_TYPE CHAR (1) NOT NULL ,
            SUBJECT_ORDER DECIMAL (18,0) NOT NULL 
);
ALTER TABLE WF_DEFAULT_SUBJECT_QUERY_DEF
    ADD CONSTRAINT DEFAULTSUBJQUERYPK 
PRIMARY KEY (ID);

##系统全局层次的任务列表标题数据来源定义
CREATE TABLE WF_SYS_SUBJECT_SC_DEF
(
            ID VARCHAR (32) NOT NULL ,
            PROC_DEF_UNIQUE_ID VARCHAR (32) NOT NULL ,
            SYS_SUBJECT_DEF_ID VARCHAR (32) NOT NULL ,
            DATA_FIELD_DEF_ID VARCHAR(32)
);
ALTER TABLE WF_SYS_SUBJECT_SC_DEF
    ADD CONSTRAINT SYSSUBJSCDEF_PK 
    PRIMARY KEY (ID);

##出差代理流程定义   
CREATE TABLE WF_TRIP_PROXY_PROC_DEF 
( 
    ID                 	VARCHAR(32) NOT NULL,
    PROC_DEF_ID        	VARCHAR(32) NOT NULL,
    PROC_DEF_NAME      	VARCHAR(100) NOT NULL,
    ORIGINAL_ORGAN_ID  	VARCHAR(32) NOT NULL,
    ORIGINAL_ORGAN_NAME	VARCHAR(100) NOT NULL,
    PROXY_ORGAN_ID     	VARCHAR(32) NOT NULL,
    PROXY_ORGAN_NAME   	VARCHAR(100) NOT NULL,
    IS_PROXY_EXIST_TASK CHAR(1) DEFAULT '1'
);
ALTER TABLE WF_TRIP_PROXY_PROC_DEF
    ADD CONSTRAINT TRIPPROXYPROCDEFPK 
    PRIMARY KEY (ID);
 
##出差代理关联操作定义
CREATE TABLE WF_TRIP_PROXY_OPERATION_DEF
(
    ID            	VARCHAR(32) NOT NULL,
    OPERATION_CODE	VARCHAR(32) NOT NULL,
    OPERATION_NAME	VARCHAR(100) NOT NULL
);
ALTER TABLE WF_TRIP_PROXY_OPERATION_DEF
    ADD CONSTRAINT TRIPPROOPERDEFPK 
    PRIMARY KEY (ID);
##BPMN高层次到可执行层次映射
CREATE TABLE WF_ACT_MAPPING_INFO_DEF_BPMN
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
	EXC_ACT_DEF_ID VARCHAR(32) NOT NULL,
	HIG_ACT_DEF_ID VARCHAR(32) NOT NULL
);
ALTER TABLE WF_ACT_MAPPING_INFO_DEF_BPMN
    ADD CONSTRAINT ACTHIGHEXECUTEPK
    PRIMARY KEY (ID);

CREATE TABLE WF_PROC_MAPPING_INFO_DEF_BPMN
(
	ID VARCHAR(32) NOT NULL,
	EXC_PROC_UNIQUE_ID VARCHAR(32) NOT NULL,
	HIG_PROC_UNIQUE_ID VARCHAR(32) NOT NULL
);
ALTER TABLE WF_PROC_MAPPING_INFO_DEF_BPMN
    ADD CONSTRAINT PROCHIGHEXECUTEPK
    PRIMARY KEY (ID);
##多环节实例规则定义
CREATE TABLE WF_MULTI_INSTANCE_RULE_DEF
(
    ID          VARCHAR(32) NOT NULL,
    ACT_DEF_UNIQUE_ID	VARCHAR(32) NOT NULL,
    MULTI_INSTANCE_EXPRESSION	VARCHAR(255) NOT NULL,
    RULE_TYPE	VARCHAR(32)
);
ALTER TABLE WF_MULTI_INSTANCE_RULE_DEF
    ADD CONSTRAINT MULTIINSTANCEPK 
    PRIMARY KEY (ID);
##开始环节事件
CREATE TABLE WF_START_TIMER_EVENT_DEF
(
	ID	VARCHAR(32) NOT NULL,
    PROC_DEF_UNIQUE_ID	VARCHAR(32) NOT NULL,
    RULE_TYPE VARCHAR(32) NOT NULL,
    EXPRESSION	VARCHAR(255) NOT NULL
);
ALTER TABLE WF_START_TIMER_EVENT_DEF
    ADD CONSTRAINT PROCTIMEREVENTPK 
    PRIMARY KEY (ID);
##复杂网关激活条件
CREATE TABLE WF_COMPLEX_GATEWAY_RULE_DEF
(
    ID          VARCHAR(32) NOT NULL,
    ACT_DEF_UNIQUE_ID	VARCHAR(32) NOT NULL,
    ACTIVATION_CONDITION	VARCHAR(255),
    RULE_TYPE	VARCHAR(32)
);
ALTER TABLE WF_COMPLEX_GATEWAY_RULE_DEF
    ADD CONSTRAINT COMPLEXGATEWAYPK 
    PRIMARY KEY (ID);
    
##环节事件
CREATE TABLE WF_ACT_TIMER_EVENT_DEF
(
ID VARCHAR(32) NOT NULL,
PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
ACT_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
EVENT_TYPE VARCHAR(32) NOT NULL,
RULE_TYPE VARCHAR(32) NOT NULL,
EXPRESSION VARCHAR(255) NOT NULL
);
ALTER TABLE WF_ACT_TIMER_EVENT_DEF
    ADD CONSTRAINT ACTTIMEREVENTPK 
    PRIMARY KEY (ID);

##流程实例时间事件
CREATE TABLE WF_PROCESS_TIMER_EVENT
(
ID VARCHAR(32) NOT NULL,
PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
PROCESS_ID VARCHAR (32) NOT NULL, 
ACT_DEF_UNIQUE_ID VARCHAR(32) NOT NULL,
RULE_TYPE VARCHAR(32) NOT NULL
);
ALTER TABLE WF_PROCESS_TIMER_EVENT
    ADD CONSTRAINT PROCESTIMEREVENTPK 
    PRIMARY KEY (ID);
    
##流程标题相关数据定义
CREATE TABLE WF_PROC_SUBJECT_DATA_FIELD_DEF 
( 
	 ID VARCHAR(32) NOT NULL, 
	 DATA_FIELD_DEF_UNIQUE_ID VARCHAR(32) NOT NULL, 
	 PROC_DEF_UNIQUE_ID VARCHAR(32) NOT NULL
);

ALTER TABLE WF_PROC_SUBJECT_DATA_FIELD_DEF 
   ADD CONSTRAINT PROCSUBJDATAFLDEFK
   PRIMARY KEY(ID);
 
##流程监控图之流程定义和图形模型表
CREATE TABLE WF_PROC_AND_GRAPH_DEF_MODEL
(
	ID VARCHAR(32) NOT NULL,
	PROC_DEF_ID VARCHAR(32) NOT NULL,
	PROC_DEF_NAME VARCHAR(100) NOT NULL,
	PROCESS_TYPE VARCHAR(32),
	NORM_ID VARCHAR(32) NOT NULL,
	NORM_VERSION VARCHAR(32) NOT NULL,
	CREATE_TIME CHAR(17) NOT NULL,
	MODIFY_TIME CHAR(17) NOT NULL,
	IN_USE CHAR(1) DEFAULT '1',
	MODEL_CONTENT BLOB NOT NULL,
	VENDER VARCHAR(32) NOT NULL
);
##设置主键
ALTER TABLE WF_PROC_AND_GRAPH_DEF_MODEL
 ADD CONSTRAINT PROCMODELPK PRIMARY KEY (ID);
