##环节实例索引
CREATE INDEX WF_ACT_PROCID ON WF_ACTIVITY(PROCESS_ID);

##委派实例索引
CREATE INDEX WF_ASS_ORGID ON WF_ASSIGNMENT(ORGAN_ID);
CREATE INDEX WF_ASS_ALORGID ON WF_ASSIGNMENT(ACTUAL_ORGAN_ID);
CREATE INDEX WF_ASS_ACTID ON WF_ASSIGNMENT(ACTIVITY_ID);

##环节迁移索引
CREATE INDEX WF_TRANS_ACTID ON WF_TRANSITION(ACTIVITY_ID);

##委派归档实例索引
CREATE INDEX WF_ASSEND_ALORGID ON WF_ASSIGNMENT_END(ACTUAL_ORGAN_ID);

##相关数据实例索引
CREATE INDEX WF_DF_PROCID ON WF_DATA_FIELD(PROCESS_ID);
CREATE INDEX WF_DF_PDEFID ON WF_DATA_FIELD(DATA_FIELD_DEF_UNIQUE_ID);
##任务列表增加索引
CREATE INDEX WF_TYPE_DB_ORGANID ON WF_DAI_BAN_TASK(ORGAN_ID);
CREATE INDEX WF_TYPE_DB_ACTID ON WF_DAI_BAN_TASK(ACTIVITY_ID);
CREATE INDEX WF_TYPE_DB_PROCID ON WF_DAI_BAN_TASK(PROCESS_ID);
CREATE INDEX WF_TYPE_DB_TYPE ON WF_DAI_BAN_TASK(TYPE_SUBJECT(255));
CREATE INDEX WF_TYPE_DB_PROC ON WF_DAI_BAN_TASK(PROC_SUBJECT(255));
CREATE INDEX WF_TYPE_DB_DEF ON WF_DAI_BAN_TASK(SUBJECT);

CREATE INDEX WF_TYPE_YB_ORGANID ON WF_YI_BAN_TASK(ORGAN_ID);
CREATE INDEX WF_TYPE_YB_ACTID ON WF_YI_BAN_TASK(ACTIVITY_ID);
CREATE INDEX WF_TYPE_YB_PROCID ON WF_YI_BAN_TASK(PROCESS_ID);
CREATE INDEX WF_TYPE_YB_TYPE ON WF_YI_BAN_TASK(TYPE_SUBJECT(255));
CREATE INDEX WF_TYPE_YB_PROC ON WF_YI_BAN_TASK(PROC_SUBJECT(255));
CREATE INDEX WF_TYPE_YB_DEF ON WF_YI_BAN_TASK(SUBJECT);

CREATE INDEX WF_TYPE_ED_ORGANID ON WF_END_TASK(ORGAN_ID);
CREATE INDEX WF_TYPE_ED_ACTID ON WF_END_TASK(ACTIVITY_ID);
CREATE INDEX WF_TYPE_ED_PROCID ON WF_END_TASK(PROCESS_ID);
CREATE INDEX WF_TYPE_ED_TYPE ON WF_END_TASK(TYPE_SUBJECT(255));
CREATE INDEX WF_TYPE_ED_PROC ON WF_END_TASK(PROC_SUBJECT(255));
CREATE INDEX WF_TYPE_ED_DEF ON WF_END_TASK(SUBJECT);

##流程实例标题增加索引
CREATE INDEX WF_PROC_SUBJ_IDX ON WF_PROC_SUBJECT(PROCESS_ID);
