##流程类型
CREATE TABLE WF_PROCESS_TYPE
(
    TYPE_ID VARCHAR (32) NOT NULL,
    TYPE_NAME VARCHAR (100) NOT NULL,
    DESCRIPTION VARCHAR (255),
    DISPLAY_ORDER DECIMAL(18,0),
    PARENT_ID VARCHAR(32) NOT NULL,
    TYPE_LEVEL INT,
    TYPE_PATH VARCHAR (250)
);

ALTER TABLE WF_PROCESS_TYPE
    ADD CONSTRAINT WFPROCESSTYPE_PK 
    PRIMARY KEY (TYPE_ID);
