drop table if exists DEMO_PRODUCT;

#####商品###
CREATE TABLE DEMO_PRODUCT(
  ID VARCHAR(32) NOT NULL,
  PRODUCT_CODE VARCHAR(30) NOT NULL,
  PRODUCT_NAME VARCHAR(30) DEFAULT NULL,
  PRODUCT_PRICE FLOAT(9,2) DEFAULT NULL,
  PRODUCT_NUM INT(10) DEFAULT NULL,
  PRODUCT_MANU VARCHAR(30) DEFAULT NULL,
  PRODUCT_TYPE VARCHAR(30) DEFAULT NULL,
  PRODUCT_DATE VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (ID)
);  
