##模块
INSERT INTO PUB_MODULES (MODULE_CODE,MODULE_NAME,PARENT_MODULE_CODE,IS_LEAF_MODULE,APP_CODE,MODULE_PATH,MODULE_PATH_NAME,SEQ) VALUES ('CFORM10','流程表单管理','CFORM','1','-1','CFORM#CFORM10','云表单#流程表单管理',10);

##功能
INSERT INTO PUB_FUNCTIONS (FUNCTION_CODE,FUNCTION_NAME,MODULE_CODE,SEQ) VALUES ('CFORM1000','表单操作定义','CFORM10',1);
INSERT INTO PUB_FUNCTIONS (FUNCTION_CODE,FUNCTION_NAME,MODULE_CODE,SEQ) VALUES ('CFORM1002','任务跳转URL定义','CFORM10',2);