
###
### Table: PUB_OPERATIONS
###

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01000', '查询流程定义', 'WORKFLOW0100', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01001', '增加流程定义', 'WORKFLOW0100', '00', '0', 1);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01002', '修改流程定义', 'WORKFLOW0100', '00', '0', 2);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01003', '删除流程定义', 'WORKFLOW0100', '00', '0', 3);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01010', '查询管理监控', 'WORKFLOW0101', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01011', '删除管理监控流程定义', 'WORKFLOW0101', '00', '0', 1);
    
INSERT INTO PUB_OPERATIONS (OPERATION_CODE,OPERATION_NAME,FUNCTION_CODE,OPERATION_TYPE_CODE,IS_DEFAULT,SEQ) values 
 	('WF_BPMN_PROCESS_DESIGN_QUERY','业务流程定义查询','WF_BPMN_PROCESS_DESIGN','00','1',0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_CONFIG_PROCDEF', '插件按钮配置', 'WORKFLOW_CONFIG_PROCDEF_BTN', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEF', '表单定义', 'WORKFLOW_FORM_MGR_JSP_DEF', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEL', '删除表单', 'WORKFLOW_FORM_MGR_JSP_DEF', '00', '0', 1);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_NN', '新建任务', 'WORKFLOW_TASK_LIST_DEFAULT_NEW', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASKLIST_DEFAULT_DBQ', '待办任务', 'WORKFLOW_TASK_LIST_DEFAULT_DB', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_YBQ', '已办任务', 'WORKFLOW_TASK_LIST_DEFAULT_YB', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_EQ', '办结任务', 'WORKFLOW_TASK_LIST_DEFAULT_END', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_PROCESS_RESUME_EVENT', '流程恢复监听', 'WORKFLOW_PROCESS_RESUME_EVENT', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_PROC_PERMISSION_CONF', '流程定义权限控制', 'WORKFLOW_PROC_PERMISSION_CONF', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_PLUGIN_REGISTER', '插件类型注册', 'WORKFLOW_PLUGIN_TYPE_REGISTER', '00', '1', 0);
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_PARTICIPANT_CONFIG', '参与者配置', 'WORKFLOW_PARTICIPANT_CONFIG', '00', '1', 0);
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_ALL_PROCESS_ANALYSIS','流程效率分析','WORKFLOW_ALL_PROCESS_ANALYSIS','01','1',0);
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_ALL_PART_ANALYSIS','人员绩效分析','WORKFLOW_ALL_PART_ANALYSIS','01','1',1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010000', '展现流程定义', 'jsp/workflow/infoprocessmodel/query.jsp', 'WORKFLOW01000', 'WORKFLOW0100', 'http', NULL, 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010001', '查看流程定义', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelQueryCmd/execute', 'WORKFLOW01000', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01001', '流程定义增加', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelCmd/insert', 'WORKFLOW01001', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01002', '流程定义修改', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelCmd/update', 'WORKFLOW01002', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01003', '流程定义删除', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelCmd/delete', 'WORKFLOW01003', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010100', '展现管理监控', 'jsp/workflow/manage/queryprocessdefadmin.jsp', 'WORKFLOW01010', 'WORKFLOW0101', 'http', NULL, 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010101', '查看管理监控', 'org.loushang.workflow.manage.processdef.cmd.ProcessDefManageQueryCmd/execute', 'WORKFLOW01010', 'WORKFLOW0101', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01011', '管理监控流程定义删除', 'org.loushang.workflow.manage.processdef.cmd.ProcessDefManageCmd/delete', 'WORKFLOW01011', 'WORKFLOW0101', 'http', NULL, 1);
   
INSERT INTO PUB_URLS (URL_CODE,URL_NAME,URL_CONTENT,OPERATION_CODE,FUNCTION_CODE,ACCESS_TYPE,NOTE,SEQ) values 
    ('BPMNHIGHLEVELPROCDEFQUERY','业务流程定义查询','jsp/workflow/businessprocessmodel/querybusinessprocessmodeldef.jsp','WF_BPMN_PROCESS_DESIGN_QUERY','WF_BPMN_PROCESS_DESIGN','http',null,0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_NN', '展现新建任务', 'jsp/workflow/tasklist/querynew.jsp', 'WORKFLOW_TASK_LIST_DEFAULT_NN', 'WORKFLOW_TASK_LIST_DEFAULT_NEW', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASKLIST_DEFAULT_DBQ', '展现待办任务', 'jsp/workflow/tasklist/querydaiban.jsp', 'WORKFLOW_TASKLIST_DEFAULT_DBQ', 'WORKFLOW_TASK_LIST_DEFAULT_DB', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_YBQ', '已办任务', 'jsp/workflow/tasklist/queryyiban.jsp', 'WORKFLOW_TASK_LIST_DEFAULT_YBQ', 'WORKFLOW_TASK_LIST_DEFAULT_YB', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_EQ', '办结任务', 'jsp/workflow/tasklist/queryend.jsp', 'WORKFLOW_TASK_LIST_DEFAULT_EQ', 'WORKFLOW_TASK_LIST_DEFAULT_END', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_CONFIG_PROCDEF_BTN', '插件按钮配置', 'jsp/workflow/infoprocessmodel/procdefpagebuttonconf.jsp', 'WORKFLOW_CONFIG_PROCDEF', 'WORKFLOW_CONFIG_PROCDEF_BTN', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_PROCESS_RESUME_EVENT', '事件监听扩展', 'jsp/workflow/config/eventlistenerconfig.jsp', 'WORKFLOW_PROCESS_RESUME_EVENT', 'WORKFLOW_PROCESS_RESUME_EVENT', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_PROC_PERMISSION_CONF', '流程定义权限控制', 'jsp/workflow/infoprocessmodel/procdefpermissionconfig.jsp', 'WORKFLOW_PROC_PERMISSION_CONF', 'WORKFLOW_PROC_PERMISSION_CONF', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEF', '表单定义', 'jsp/workflow/jspform/form_query.jsp', 'WORKFLOW_FORM_MGR_JSP_DEF', 'WORKFLOW_FORM_MGR_JSP_DEF', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEL', '删除表单', 'org.loushang.workflow.jspform.formdef.cmd.JspFormCmd/delete', 'WORKFLOW_FORM_MGR_JSP_DEL', 'WORKFLOW_FORM_MGR_JSP_DEF', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_PLUGIN_TYPE_REGISTER', '插件类型注册', 'jsp/workflow/infoprocessmodel/processplugintyperegister.jsp', 'WORKFLOW_PLUGIN_REGISTER', 'WORKFLOW_PLUGIN_TYPE_REGISTER', 'http', '', 0);
INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES
	('WORKFLOW_PARTICIPANT_CONFIG', '参与者配置', 'jsp/workflow/infoprocessmodel/parturldef.jsp', 'WORKFLOW_PARTICIPANT_CONFIG', 'WORKFLOW_PARTICIPANT_CONFIG', 'http', '', 0);
INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES
	('WORKFLOW_ALL_PROC_ANALYSIS_URL','流程效率分析','jsp/workflow/analysis/performance/allprocessperformancecompare.jsp','WORKFLOW_ALL_PROCESS_ANALYSIS','WORKFLOW_ALL_PROCESS_ANALYSIS','http',NULL,0);
INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES
	('WORKFLOW_ALL_PART_ANALYSIS_URL','人员绩效分析','jsp/workflow/analysis/performance/allparticipantperformancecompare.jsp','WORKFLOW_ALL_PART_ANALYSIS','WORKFLOW_ALL_PART_ANALYSIS','http',NULL,0);
