
###
### Table: PUB_MENU_ITEM
###


INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF, ICON) VALUES 
    ('WORKFLOW', '工作流', NULL, NULL, NULL, 'WORKFLOW', '-1', NULL, 'platform/img/bpm.png');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW01', '流程管理', NULL, NULL, NULL, 'WORKFLOW01', '-1', NULL);

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW02', '流程统计分析', NULL, NULL, NULL, 'WORKFLOW02', '-1', NULL);


INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW0101', '管理监控', 'jsp/workflow/manage/queryprocessdefadmin.jsp', NULL, 'WORKFLOW0101', 'WORKFLOW01', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW0100', '流程定义', 'jsp/workflow/infoprocessmodel/query.jsp', NULL, 'WORKFLOW0100', 'WORKFLOW01', '-1', '1');
   
INSERT INTO PUB_MENU_ITEM (MENU_ID,MENU_NAME,REQUEST_ACTION,TARGET,FUNCTION_CODE,MODULE_CODE,APP_CODE,IS_LEAF) VALUES 
	('WF_BPMN_PROCESS_MODELING_DEF','业务流程定义','jsp/workflow/businessprocessmodel/querybusinessprocessmodeldef.jsp',null,'WF_BPMN_PROCESS_DESIGN','WORKFLOW01','-1','1');
	
INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00009', '任务列表', NULL, NULL, NULL, 'WORKFLOW_TASK_LIST', '-1', '0');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00011', '新建任务', 'jsp/workflow/tasklist/querynew.jsp', NULL, 'WORKFLOW_TASK_LIST_DEFAULT_NEW', 'WORKFLOW_TASK_LIST', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00012', '待办任务', 'jsp/workflow/tasklist/querydaiban.jsp', NULL, 'WORKFLOW_TASK_LIST_DEFAULT_DB', 'WORKFLOW_TASK_LIST', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00013', '已办任务', 'jsp/workflow/tasklist/queryyiban.jsp', NULL, 'WORKFLOW_TASK_LIST_DEFAULT_YB', 'WORKFLOW_TASK_LIST', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00014', '办结任务', 'jsp/workflow/tasklist/queryend.jsp', NULL, 'WORKFLOW_TASK_LIST_DEFAULT_END', 'WORKFLOW_TASK_LIST', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00036', '配置管理', NULL, NULL, NULL, 'WORKFLOW_CONFIG_MGR', '-1', '0');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00043', '流程定义配置', NULL, NULL, NULL, 'WORKFLOW_CONFIG_PROCDEF', '-1', '0');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00044', '插件按钮配置', 'jsp/workflow/infoprocessmodel/procdefpagebuttonconf.jsp', NULL, 'WORKFLOW_CONFIG_PROCDEF_BTN', 'WORKFLOW_CONFIG_PROCDEF', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00045', '工作流属性配置', NULL, NULL, NULL, 'WORKFLOW_CONFIG_PROCDEF', '-1', '0');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00046', '事件监听扩展', 'jsp/workflow/config/eventlistenerconfig.jsp', NULL, 'WORKFLOW_PROCESS_RESUME_EVENT', 'WORKFLOW_PROPERTY_CONFIG', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00047', '流程定义权限控制', 'jsp/workflow/infoprocessmodel/procdefpermissionconfig.jsp', NULL, 'WORKFLOW_PROC_PERMISSION_CONF', 'WORKFLOW_CONFIG_PROCDEF', '-1', '1');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00052', '表单管理', NULL, NULL, NULL, 'WORKFLOW_FORM_MGR', '-1', '0');

INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00059', '表单定义', 'jsp/workflow/jspform/form_query.jsp', NULL, 'WORKFLOW_FORM_MGR_JSP_DEF', 'WORKFLOW_FORM_MGR', '-1', '1');
    
INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_00060', '插件类型注册', 'jsp/workflow/infoprocessmodel/processplugintyperegister.jsp', NULL, 'WORKFLOW_PLUGIN_TYPE_REGISTER', 'WORKFLOW_CONFIG_PROCDEF', '-1', '1');
INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES 
    ('WORKFLOW_MENU_PART', '参与者配置', 'jsp/workflow/infoprocessmodel/parturldef.jsp', NULL, 'WORKFLOW_PARTICIPANT_CONFIG', 'WORKFLOW_CONFIG_PROCDEF', '-1', '1');
INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES
	('WORKFLOW_PROC_ANALYSIS', '流程统计分析', NULL, NULL, NULL, 'WORKFLOW01', '-1', NULL);
INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES
	('WORKFLOW_ALL_PROCESS_ANALYSIS', '流程效率分析', 'jsp/workflow/analysis/performance/allprocessperformancecompare.jsp', NULL, 'WORKFLOW_ALL_PROCESS_ANALYSIS', 'WORKFLOW_PROC_ANALYSIS', '-1', '1');
INSERT INTO PUB_MENU_ITEM (MENU_ID, MENU_NAME, REQUEST_ACTION, TARGET, FUNCTION_CODE, MODULE_CODE, APP_CODE, IS_LEAF) VALUES
	('WORKFLOW_ALL_PART_ANALYSIS', '人员绩效分析', 'jsp/workflow/analysis/performance/allparticipantperformancecompare.jsp', NULL, 'WORKFLOW_ALL_PART_ANALYSIS', 'WORKFLOW_PROC_ANALYSIS', '-1', '1');

###
### Table: PUB_MENU_STRU
###


INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW00000000000000000000', '1', 'WORKFLOW', 'WORKFLOW', 'WORKFLOW', '工作流', 0);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW000000000000000000001', '1', 'WORKFLOW01', 'WORKFLOW', 'WORKFLOW#WORKFLOW01', '工作流#流程管理', 1);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW0000000000000000000010', '1', 'WORKFLOW0100', 'WORKFLOW01', 'WORKFLOW#WORKFLOW01#WORKFLOW0100', '工作流#流程管理#流程定义', 1);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW0000000000000000000011', '1', 'WORKFLOW0101', 'WORKFLOW01', 'WORKFLOW#WORKFLOW01#WORKFLOW0101', '工作流#流程管理#管理监控', 2);
   
INSERT INTO PUB_MENU_STRU (MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,MENU_PATH,PATH_NAME,SEQ) VALUES 
	('WF_BPMN_PROCESS_MODELING_DEF','1','WF_BPMN_PROCESS_MODELING_DEF','WORKFLOW01','WORKFLOW#WORKFLOW01#WF_BPMN_PROCESS_MODELING_DEF','工作流#流程管理#业务流程定义',4);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00009', '1', 'WORKFLOW_MENU_00009', 'WORKFLOW', 'WORKFLOW#WORKFLOW_MENU_00009', '工作流#任务列表', 0);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00011', '1', 'WORKFLOW_MENU_00011', 'WORKFLOW_MENU_00009', 'WORKFLOW#WORKFLOW_MENU_00009#WORKFLOW_MENU_00011', '工作流#任务列表#新建任务', 1);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00012', '1', 'WORKFLOW_MENU_00012', 'WORKFLOW_MENU_00009', 'WORKFLOW#WORKFLOW_MENU_00009#WORKFLOW_MENU_00012', '工作流#任务列表#待办任务', 2);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00013', '1', 'WORKFLOW_MENU_00013', 'WORKFLOW_MENU_00009', 'WORKFLOW#WORKFLOW_MENU_00009#WORKFLOW_MENU_00013', '工作流#任务列表#已办任务', 3);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00014', '1', 'WORKFLOW_MENU_00014', 'WORKFLOW_MENU_00009', 'WORKFLOW#WORKFLOW_MENU_00009#WORKFLOW_MENU_00014', '工作流#任务列表#办结任务', 4);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00036', '1', 'WORKFLOW_MENU_00036', 'WORKFLOW', 'WORKFLOW#WORKFLOW_MENU_00036', '工作流#配置管理', 4);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00043', '1', 'WORKFLOW_MENU_00043', 'WORKFLOW_MENU_00036', 'WORKFLOW#WORKFLOW_MENU_00036#WORKFLOW_MENU_00043', '工作流#配置管理#流程定义配置', 2);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00044', '1', 'WORKFLOW_MENU_00044', 'WORKFLOW_MENU_00043', 'WORKFLOW#WORKFLOW_MENU_00036#WORKFLOW_MENU_00043#WORKFLOW_MENU_00044', '工作流#配置管理#流程定义配置#插件按钮配置', 1);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00045', '1', 'WORKFLOW_MENU_00045', 'WORKFLOW_MENU_00036', 'WORKFLOW#WORKFLOW_MENU_00036#WORKFLOW_MENU_00045', '工作流#配置管理#工作流属性配置', 3);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00046', '1', 'WORKFLOW_MENU_00046', 'WORKFLOW_MENU_00045', 'WORKFLOW#WORKFLOW_MENU_00036#WORKFLOW_MENU_00045#WORKFLOW_MENU_00046', '工作流#配置管理#工作流属性配置#流程恢复监听', 1);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00047', '1', 'WORKFLOW_MENU_00047', 'WORKFLOW_MENU_00045', 'WORKFLOW#WORKFLOW_MENU_00036#WORKFLOW_MENU_00045#WORKFLOW_MENU_00047', '工作流#配置管理#工作流属性配置#流程定义权限控制', 2);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00052', '1', 'WORKFLOW_MENU_00052', 'WORKFLOW', 'WORKFLOW#WORKFLOW_MENU_00052', '工作流#表单管理', 2);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00059', '1', 'WORKFLOW_MENU_00059', 'WORKFLOW_MENU_00052', 'WORKFLOW#WORKFLOW_MENU_00052#WORKFLOW_MENU_00059', '工作流#表单管理#表单定义', 1);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_00060', '1', 'WORKFLOW_MENU_00060', 'WORKFLOW_MENU_00043', 'WORKFLOW#WORKFLOW_MENU_00036#WORKFLOW_MENU_00043#WORKFLOW_MENU_00060', '工作流#配置管理#流程定义配置#插件类型注册', 2);
INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES 
    ('WORKFLOW_MENU_PART', '1', 'WORKFLOW_MENU_PART', 'WORKFLOW_MENU_00043', 'WORKFLOW#WORKFLOW_MENU_00036#WORKFLOW_MENU_00043#WORKFLOW_MENU_PART', '工作流#配置管理#流程定义配置#参与者配置', 2);

INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES
	('WORKFLOW_PROC_ANALYSIS', '1', 'WORKFLOW_PROC_ANALYSIS', 'WORKFLOW', 'WORKFLOW#WORKFLOW_PROC_ANALYSIS', '工作流#流程统计分析', 8);
INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES
	('WORKFLOW_ALL_PROCESS_ANALYSIS', '1', 'WORKFLOW_ALL_PROCESS_ANALYSIS', 'WORKFLOW_PROC_ANALYSIS', 'WORKFLOW#WORKFLOW_PROC_ANALYSIS#WORKFLOW_ALL_PROCESS_ANALYSIS', '工作流#流程统计分析#流程效率分析', 0);
INSERT INTO PUB_MENU_STRU (MENU_STRU_ID, MENU_TYPE_ID, MENU_ID, PARENT_MENU_ID, MENU_PATH, PATH_NAME, SEQ) VALUES
	('WORKFLOW_ALL_PART_ANALYSIS', '1', 'WORKFLOW_ALL_PART_ANALYSIS', 'WORKFLOW_PROC_ANALYSIS', 'WORKFLOW#WORKFLOW_PROC_ANALYSIS#WORKFLOW_ALL_PART_ANALYSIS', '工作流#流程统计分析#人员绩效分析', 1);
