--表单操作
INSERT INTO PUB_OPERATIONS (OPERATION_CODE,OPERATION_NAME,FUNCTION_CODE,OPERATION_TYPE_CODE,IS_DEFAULT,SEQ) VALUES ('CFORM10000','表单操作定义','CFORM1000','00','1',1);
INSERT INTO PUB_URLS (URL_CODE,URL_NAME,URL_CONTENT,OPERATION_CODE,FUNCTION_CODE,SEQ,ACCESS_TYPE) VALUES('CFORM100000','表单操作定义','jsp/cform/btn/querybtn.jsp','CFORM10000','CFORM1000',0,'http');

--任务列表跳转URL
INSERT INTO PUB_OPERATIONS (OPERATION_CODE,OPERATION_NAME,FUNCTION_CODE,OPERATION_TYPE_CODE,IS_DEFAULT,SEQ) VALUES ('CFORM10002','任务跳转URL定义','CFORM1002','00','1',2);
INSERT INTO PUB_URLS (URL_CODE,URL_NAME,URL_CONTENT,OPERATION_CODE,FUNCTION_CODE,SEQ,ACCESS_TYPE) VALUES('CFORM100020','任务跳转URL定义','jsp/cform/procdef/tasklistforwardurldef.jsp','CFORM10002','CFORM1002',0,'http');