--流程监控配置
CREATE TABLE WF_MONITOR_PROPERTY_CONFIG
(
    ID VARCHAR (32) NOT NULL ,
    PROPERTY_KEY VARCHAR (32) NOT NULL ,
    PROPERTY_VALUE VARCHAR (100) NOT NULL ,
    PROPERTY_DESCRIPTION VARCHAR (100) 
);
ALTER TABLE WF_MONITOR_PROPERTY_CONFIG
    ADD CONSTRAINT MONITORCONFIG_PK 
    PRIMARY KEY (ID);
