##环节——表单关联
ALTER TABLE CF_ACT_FORM
    ADD CONSTRAINT CF_AF_FK1 FOREIGN KEY (ACT_DEF_UNIQUE_ID)
    REFERENCES WF_ACTIVITY_DEF (ID);

ALTER TABLE CF_ACT_FORM
    ADD CONSTRAINT CF_AF_FK2 FOREIGN KEY (FORM_ID)
    REFERENCES CF_FORM (FORM_ID);

##环节——表单域权限
ALTER TABLE CF_ACT_FORM_ACL
    ADD CONSTRAINT CF_AFA_FK1 FOREIGN KEY (ACT_DEF_UNIQUE_ID)
    REFERENCES WF_ACTIVITY_DEF (ID);

ALTER TABLE CF_ACT_FORM_ACL
    ADD CONSTRAINT CF_AFA_FK2 FOREIGN KEY (FORM_ID)
    REFERENCES CF_FORM (FORM_ID);

##环节——表单操作按钮
ALTER TABLE CF_ACT_FORM_BTN
    ADD CONSTRAINT CF_AFB_FK1 FOREIGN KEY (ACT_DEF_UNIQUE_ID)
    REFERENCES WF_ACTIVITY_DEF (ID);

ALTER TABLE CF_ACT_FORM_BTN
    ADD CONSTRAINT CF_AFB_FK2 FOREIGN KEY (FORM_ID)
    REFERENCES CF_FORM (FORM_ID);

ALTER TABLE CF_ACT_FORM_BTN
    ADD CONSTRAINT CF_AFB_FK3 FOREIGN KEY (BTN_DEF_ID)
    REFERENCES CF_BTN (ACTION_ID);

##流程类型层次任务标题来源
ALTER TABLE CF_TYPE_SUBJECT_SC_FIELD_DEF
    ADD CONSTRAINT CF_TSSFD_FK1 FOREIGN KEY (ACT_DEF_UNIQUE_ID)
    REFERENCES WF_ACTIVITY_DEF (ID);

ALTER TABLE CF_TYPE_SUBJECT_SC_FIELD_DEF
    ADD CONSTRAINT CF_TSSFD_FK2 FOREIGN KEY (FORM_ID)
    REFERENCES CF_FORM (FORM_ID);
    
##流程定义层次任务标题来源
ALTER TABLE CF_PROC_SUBJECT_SC_FIELD_DEF
    ADD CONSTRAINT CF_PSSFD_FK1 FOREIGN KEY (ACT_DEF_UNIQUE_ID)
    REFERENCES WF_ACTIVITY_DEF (ID);

ALTER TABLE CF_PROC_SUBJECT_SC_FIELD_DEF
    ADD CONSTRAINT CF_PSSFD_FK2 FOREIGN KEY (FORM_ID)
    REFERENCES CF_FORM (FORM_ID);
    
##表单操作
ALTER TABLE CF_BTN
    ADD CONSTRAINT CF_BTN_FK1 FOREIGN KEY (ACTION_TYPE)
    REFERENCES CF_BTN_TYPE (ID);