-- 菜单项
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,MODULE_CODE,APP_CODE,IS_LEAF,ICON) VALUES('CPORTAL','CPortal','jsp/cportal/introduce.jsp','CPORTAL','-1','0','platform/img/cportal.png');

INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,MODULE_CODE,APP_CODE,IS_LEAF) VALUES('CPORTAL01','Page Management','CPORTAL01','-1','0');
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) VALUES('CPORTAL0100','Page Definition','jsp/cportal/page/querypage.jsp','1','CPORTAL01','CPORTAL0100','-1');
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) VALUES('CPORTAL0101','Widget Definition','jsp/cportal/widget/querywidget.jsp','1','CPORTAL01','CPORTAL0101','-1');

-- 菜单结构
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) VALUES ('CPORTAL','1','CPORTAL','CPORTAL',11,'CPORTAL','CPortal');

INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) VALUES ('CPORTAL01','1','CPORTAL01','CPORTAL',1,'CPORTAL#CPORTAL01','CPortal#Page Management');
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) VALUES ('CPORTAL0100','1','CPORTAL0100','CPORTAL01',0,'CPORTAL#CPORTAL01#CPORTAL0100','CPortal#Page Management#Page Definition');
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) VALUES ('CPORTAL0101','1','CPORTAL0101','CPORTAL01',1,'CPORTAL#CPORTAL01#CPORTAL0101','CPortal#Page Management#Widget Definition');