
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01000', 'Query workflow definition', 'WORKFLOW0100', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01001', 'Add workflow definition', 'WORKFLOW0100', '00', '0', 1);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01002', 'Edit workflow definition', 'WORKFLOW0100', '00', '0', 2);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01003', 'Delete workflow definition', 'WORKFLOW0100', '00', '0', 3);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
   ('WORKFLOW01010', 'Query management monitoring', 'WORKFLOW0101', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
    ('WORKFLOW01011', 'Delete management monitoring workflow definition', 'WORKFLOW0101', '00', '0', 1);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW01020', 'Workflow Type', 'WORKFLOW0102', '00', '1', 0);
    
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_CONFIG_PROCDEF', 'Plugin Button', 'WORKFLOW_CONFIG_PROCDEF_BTN', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEF', 'Report definition', 'WORKFLOW_FORM_MGR_JSP_DEF', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEL', 'Delete report', 'WORKFLOW_FORM_MGR_JSP_DEF', '00', '0', 1);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_NN', 'Create Task', 'WORKFLOW_TASK_LIST_DEFAULT_NEW', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASKLIST_DEFAULT_DBQ', 'To-Do Task', 'WORKFLOW_TASK_LIST_DEFAULT_DB', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_YBQ', 'Done Task', 'WORKFLOW_TASK_LIST_DEFAULT_YB', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_EQ', 'End Task', 'WORKFLOW_TASK_LIST_DEFAULT_END', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_PROCESS_RESUME_EVENT', 'Workflow resume monitoring', 'WORKFLOW_PROCESS_RESUME_EVENT', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES 
    ('WORKFLOW_PROC_PERMISSION_CONF', 'Workflow Permit', 'WORKFLOW_PROC_PERMISSION_CONF', '00', '1', 0);

INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_PLUGIN_REGISTER', 'Plugin Register', 'WORKFLOW_PLUGIN_TYPE_REGISTER', '00', '1', 0);
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_PARTICIPANT_CONFIG', 'Participants config', 'WORKFLOW_PARTICIPANT_CONFIG', '00', '1', 0);
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_ALL_PROCESS_ANALYSIS','Workflow Analysis','WORKFLOW_ALL_PROCESS_ANALYSIS','01','1',0);
INSERT INTO PUB_OPERATIONS (OPERATION_CODE, OPERATION_NAME, FUNCTION_CODE, OPERATION_TYPE_CODE, IS_DEFAULT, SEQ) VALUES
	('WORKFLOW_ALL_PART_ANALYSIS','Organ Analysis','WORKFLOW_ALL_PART_ANALYSIS','01','1',1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010000', 'Display workflow definition', 'jsp/workflow/infoprocessmodel/query.jsp', 'WORKFLOW01000', 'WORKFLOW0100', 'http', NULL, 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010001', 'View workflow definition', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelQueryCmd/execute', 'WORKFLOW01000', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01001', 'Workflow definition add', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelCmd/insert', 'WORKFLOW01001', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01002', 'Workflow definition edit', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelCmd/update', 'WORKFLOW01002', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01003', 'Workflow definition delete', 'org.loushang.workflow.infoprocessmodel.definition.cmd.InfoProcessDefModelCmd/delete', 'WORKFLOW01003', 'WORKFLOW0100', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010100', 'Display management monitoring', 'jsp/workflow/manage/queryprocessdefadmin.jsp', 'WORKFLOW01010', 'WORKFLOW0101', 'http', NULL, 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010101', 'View management monitoring', 'org.loushang.workflow.manage.processdef.cmd.ProcessDefManageQueryCmd/execute', 'WORKFLOW01010', 'WORKFLOW0101', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW01011', 'Delete management monitoring work flow definition', 'org.loushang.workflow.manage.processdef.cmd.ProcessDefManageCmd/delete', 'WORKFLOW01011', 'WORKFLOW0101', 'http', NULL, 1);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW010200', 'Workflow type query', 'jsp/workflow/processtype/query.jsp', 'WORKFLOW01020', 'WORKFLOW0102', 'http', NULL, 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_NN', 'Display task newly created', 'jsp/workflow/tasklist/querynew.jsp', 'WORKFLOW_TASK_LIST_DEFAULT_NN', 'WORKFLOW_TASK_LIST_DEFAULT_NEW', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASKLIST_DEFAULT_DBQ', 'Display task to be done', 'jsp/workflow/tasklist/querydaiban.jsp', 'WORKFLOW_TASKLIST_DEFAULT_DBQ', 'WORKFLOW_TASK_LIST_DEFAULT_DB', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_YBQ', 'Done Task', 'jsp/workflow/tasklist/queryyiban.jsp', 'WORKFLOW_TASK_LIST_DEFAULT_YBQ', 'WORKFLOW_TASK_LIST_DEFAULT_YB', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_TASK_LIST_DEFAULT_EQ', 'End Task', 'jsp/workflow/tasklist/queryend.jsp', 'WORKFLOW_TASK_LIST_DEFAULT_EQ', 'WORKFLOW_TASK_LIST_DEFAULT_END', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_CONFIG_PROCDEF_BTN', 'Plugin Button', 'jsp/workflow/infoprocessmodel/procdefpagebuttonconf.jsp', 'WORKFLOW_CONFIG_PROCDEF', 'WORKFLOW_CONFIG_PROCDEF_BTN', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_PROCESS_RESUME_EVENT', 'Event Listener', 'jsp/workflow/config/eventlistenerconfig.jsp', 'WORKFLOW_PROCESS_RESUME_EVENT', 'WORKFLOW_PROCESS_RESUME_EVENT', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_PROC_PERMISSION_CONF', 'Workflow Permit', 'jsp/workflow/infoprocessmodel/procdefpermissionconfig.jsp', 'WORKFLOW_PROC_PERMISSION_CONF', 'WORKFLOW_PROC_PERMISSION_CONF', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEF', 'Report definition', 'jsp/workflow/jspform/form_query.jsp', 'WORKFLOW_FORM_MGR_JSP_DEF', 'WORKFLOW_FORM_MGR_JSP_DEF', 'http', '', 0);

INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_FORM_MGR_JSP_DEL', 'Delete report', 'org.loushang.workflow.jspform.formdef.cmd.JspFormCmd/delete', 'WORKFLOW_FORM_MGR_JSP_DEL', 'WORKFLOW_FORM_MGR_JSP_DEF', 'http', '', 0);
    
INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES 
    ('WORKFLOW_PLUGIN_TYPE_REGISTER', 'Plugin Register', 'jsp/workflow/infoprocessmodel/processplugintyperegister.jsp', 'WORKFLOW_PLUGIN_REGISTER', 'WORKFLOW_PLUGIN_TYPE_REGISTER', 'http', '', 0);
INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES
	('WORKFLOW_PARTICIPANT_CONFIG', 'Participants config', 'jsp/workflow/infoprocessmodel/parturldef.jsp', 'WORKFLOW_PARTICIPANT_CONFIG', 'WORKFLOW_PARTICIPANT_CONFIG', 'http', '', 0);
INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES
	('WORKFLOW_ALL_PROC_ANALYSIS_URL','Workflow Analysis','jsp/workflow/analysis/performance/allprocessperformancecompare.jsp','WORKFLOW_ALL_PROCESS_ANALYSIS','WORKFLOW_ALL_PROCESS_ANALYSIS','http',NULL,0);
INSERT INTO PUB_URLS (URL_CODE, URL_NAME, URL_CONTENT, OPERATION_CODE, FUNCTION_CODE, ACCESS_TYPE, NOTE, SEQ) VALUES
	('WORKFLOW_ALL_PART_ANALYSIS_URL','Organ Analysis','jsp/workflow/analysis/performance/allparticipantperformancecompare.jsp','WORKFLOW_ALL_PART_ANALYSIS','WORKFLOW_ALL_PART_ANALYSIS','http',NULL,0);

