--商品
CREATE TABLE DEMO_PRODUCT(
  ID varchar2(32) NOT NULL,
  PRODUCT_CODE VARCHAR2(30) NOT NULL,
  PRODUCT_NAME VARCHAR2(30) DEFAULT NULL,
  PRODUCT_PRICE NUMBER(9,2) DEFAULT NULL,
  PRODUCT_NUM INTEGER DEFAULT NULL,
  PRODUCT_MANU VARCHAR2(30) DEFAULT NULL,
  PRODUCT_TYPE VARCHAR2(30) DEFAULT NULL,
  PRODUCT_DATE VARCHAR2(30) DEFAULT NULL,
  PRIMARY KEY (ID)
);  