-- for sybase  
--BSP所有的数据库初始化脚本
----创建BSP中的相关表以及视图

----组织结构
---业务流水号表ͼ
CREATE TABLE PUB_IDTABLE (
	ID_ID VARCHAR(30) NOT NULL ,
	ID_VALUE INT NOT NULL ,
	ID_NAME VARCHAR(50) NOT NULL ,
	ID_PREFIX VARCHAR(60) NULL,
	IS_PREFIX CHAR(1) NOT NULL ,
	ID_LENGTH INT NOT NULL,
	IS_SUFFIX CHAR(1)  NULL,
	ID_SUFFIX VARCHAR(60) NULL,
	IS_GLOBAL CHAR(1)  NOT NULL,
	ORGAN_ID VARCHAR(30) NULL,
	ID_TYPE CHAR(2) NULL,
	ID_DATE CHAR(8) NULL
)  ;

---组织类型
CREATE TABLE PUB_ORGAN_TYPE
(
            ORGAN_TYPE VARCHAR (10)    NOT NULL  ,
            TYPE_NAME VARCHAR (60)     NOT NULL ,
            PARENT_TYPE VARCHAR (10)   NOT NULL ,
            IN_USE CHAR (1) DEFAULT '1' NOT NULL
) ;

--组织结构类型
CREATE TABLE PUB_STRU_TYPE
(
            STRU_TYPE VARCHAR (10) 	NOT NULL  ,
            TYPE_NAME VARCHAR (60) NOT NULL ,
            ROOT_ID VARCHAR (30) NOT NULL ,
            IS_DEFAULT CHAR (1) DEFAULT '0' NOT NULL ,
            NOTE VARCHAR (250)  NULL,
            IN_USE CHAR (1) DEFAULT '1' NOT NULL
) ;

--组织结构规则
CREATE TABLE PUB_STRU_RULE
(
            RULE_ID VARCHAR (20) NOT NULL ,
            STRU_TYPE VARCHAR (10) NOT NULL ,
            SRC_REF VARCHAR (10) NOT NULL ,
            TARGET_REF VARCHAR (10) NOT NULL ,
            RULE_NOTE VARCHAR (250) NULL
) ;

--组织
CREATE TABLE PUB_ORGAN
(
            ORGAN_ID VARCHAR (30) NOT NULL ,
            ORGAN_CODE VARCHAR (30) NOT NULL ,
            ORGAN_NAME VARCHAR (80) NOT NULL ,
            SHORT_NAME VARCHAR (40) NULL,
            ORGAN_TYPE VARCHAR (10) NOT NULL ,
            IN_USE CHAR (1) DEFAULT '1' NOT NULL
) ;
---组织结构表
CREATE TABLE PUB_STRU
(
            STRU_ID VARCHAR (30) NOT NULL ,
            ORGAN_ID VARCHAR (30) NOT NULL ,
            STRU_TYPE VARCHAR (10) NOT NULL ,
            PARENT_ID VARCHAR (30) NULL,
            STRU_LEVEL INT NOT NULL ,
            STRU_PATH VARCHAR (1000) NOT NULL ,
            STRU_ORDER INT DEFAULT 1 NOT NULL ,
            IS_LEAF CHAR (1) DEFAULT '0' NOT NULL ,
            IN_USE CHAR (1) DEFAULT '1' NOT NULL
) ;
--组织结构扩展
CREATE TABLE PUB_STRU_EXT
(
	ID VARCHAR (30) NOT NULL ,
	TYPE CHAR (2) NOT NULL,
	SRC_ID VARCHAR (30) NOT NULL,
	TARGET_ID VARCHAR (30) NOT NULL,
	STRU_TYPE VARCHAR (10) NOT NULL ,
	STRU_ID VARCHAR (30) NOT NULL
);

----权限相关
--数据类型表
CREATE TABLE PUB_DATA_TYPE
(
	DATA_TYPE_CODE VARCHAR(10) NOT NULL,
	DATA_TYPE_NAME VARCHAR(30) NOT NULL,
	IS_ORGAN CHAR(1) NOT NULL,
	SOURCE_TABLE VARCHAR(30) NULL ,
	SOURCE_TABLE_DES VARCHAR(30) NULL,
	SEL_COL VARCHAR(30) NULL,
	SEL_COL_DES VARCHAR(60) NULL,
	DISP_COL VARCHAR(30) NULL,
	DISP_COL_DES VARCHAR(60) NULL,
	IS_USE_WHERE CHAR(1) DEFAULT '0' NULL ,
	WHERE_CONDITION VARCHAR(600) NULL,
	NOTE VARCHAR(30) NULL
);

--组织参数类型表
CREATE TABLE PUB_ORGAN_PARMS_TYPE
(
	ORGAN_PARMS_NAME VARCHAR(30) NOT NULL,
	ORGAN_PARMS_DES VARCHAR(250) NOT NULL,
	DATA_SOURCE CHAR(1) DEFAULT '0' NOT NULL,
	ENUM_NAME VARCHAR(30) NULL,
	ENUM_DES VARCHAR(30) NULL,
	SOURCE_TABLE_NAME VARCHAR(30) NULL,
	SOURCE_TABLE_DES VARCHAR(30) NULL,
	SEL_COL VARCHAR(30) NULL,
	SEL_COL_DES VARCHAR(60) NULL,
	DISP_COL VARCHAR(30) NULL,
	DISP_COL_DES VARCHAR(60) NULL,
	IS_USE_WHERE CHAR(1) DEFAULT '0' NULL,
	WHERE_CONDITION VARCHAR(600) NULL,
	NOTE VARCHAR(250) NULL
);

--组织参数表
CREATE TABLE PUB_ORGAN_PARMS
(
	ORGAN_ID VARCHAR(30) NOT NULL,
	PARMS_NAME VARCHAR(30) NOT NULL,
	PARMS_VALUE VARCHAR(250) NOT NULL,
	NOTE VARCHAR(250) NULL
);

--------------------用户------------------------
----用户类型
CREATE TABLE PUB_USER_TYPE
(
    USER_TYPE_CODE VARCHAR(10) NOT NULL,
    USER_TYPE_NAME VARCHAR(60) NOT NULL,
    DESCRIPTION VARCHAR(200) NULL,
    IS_USE  CHAR(1) NOT NULL
);

CREATE TABLE PUB_USERS
(
    USER_ID VARCHAR (30) NOT NULL ,
 	USER_TYPE_CODE VARCHAR (10) NULL,
    USER_NAME VARCHAR (30) NOT NULL ,
    PASSWORD VARCHAR (128) NOT NULL ,
    ACCOUNT_STATUS CHAR (2) DEFAULT '11' NOT NULL ,
    IS_SYS CHAR (1) DEFAULT '0' NOT NULL ,
    CREATE_TIME CHAR (17) NOT NULL ,
    LOCK_TIME CHAR (17) NULL,
    EXPIRED_TIME CHAR (17) NULL,
    PWD_UPT_TIME CHAR (17) NULL,
	PWD_TIME CHAR (17) NULL
) ;

----用户员工对应表
CREATE TABLE PUB_USER_EMPLOYEE(
	USER_ID VARCHAR(30) NOT NULL,
	CORPORATION_ID VARCHAR(30) NOT NULL,
	DEPARTMENT_ID VARCHAR(30) NOT NULL,
	EMPLOYEE_ID VARCHAR(30) NULL
);
-----用户策略
CREATE TABLE PUB_USER_POLICY(
    USER_ID VARCHAR (30) NOT NULL ,
    IS_USE_IP CHAR(1) NOT NULL,
    IP_POLICY_VALUE VARCHAR(200) NULL ,
    MAX_SESSION_NUMBER INTEGER
);
--用户数据权限 LIUCHH　20130904　增加是否默认值  IS_DEFAULT
CREATE TABLE PUB_USER_DATA(
    ID  VARCHAR(30) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    ORGAN_TYPE VARCHAR(10) NOT NULL,
    CODE VARCHAR(30),
    NAME VARCHAR(80),
    STRU_TYPE VARCHAR(10),
    IS_SCOPE CHAR(1),
    IS_DEFAULT VARCHAR(1) WITH DEFAULT  '0'
);
-----用户数据权限对应
CREATE TABLE PUB_USER_DATA_PERMIT
(
    USER_DATA_PERMIT_ID VARCHAR (30) NOT NULL ,
	USER_ID VARCHAR (30) NOT NULL ,
 	OBJECT_VALUE VARCHAR (30) NOT NULL ,
	OBJECT_NAME VARCHAR (80) NULL,
    DATA_TYPE_CODE VARCHAR (10) NOT NULL ,
    IS_DEFAULT CHAR (1) DEFAULT '0' NOT NULL ,
    STRU_ID VARCHAR (30)  NULL,
    STRU_TYPE VARCHAR (10)  NULL,
    SCOPE_TYPE VARCHAR (1)  NULL,
    SCOPE_VALUE VARCHAR (30)  NULL,
	SCOPE_NAME VARCHAR (80) NULL,
    START_TIME CHAR (17) NULL,
    END_TIME CHAR (17) NULL
) ;

 ---在线用户  liuchh 20130828 为适应存放各类服务器端生成的session_id 长度，将SESSION_ID扩大到VARCHAR(100)
CREATE TABLE PUB_ONLINE
(
    SESSION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR (30) NOT NULL ,
    USER_NAME VARCHAR(30) NULL,
    CORPORATION_ID VARCHAR(30) NULL,
    LOGIN_TIME CHAR(17) NULL,
    LOGOUT_TIME CHAR(17) NULL,
    REMOTEADDR  VARCHAR(80) NULL
);
-- 添加字段服务端sessionId
ALTER TABLE PUB_ONLINE ADD SVR_SESSION_ID varchar(100) NOT NULL;
-- 添加字段认证客户端类别clientType(如0-Browser, 1-App)
ALTER TABLE PUB_ONLINE ADD CLIENT_TYPE varchar(2);
--------------------------------------------------------菜单--------------------------------------
--系统菜单类型
CREATE TABLE PUB_MENU_TYPE(
	MENU_TYPE_ID VARCHAR(10) NOT NULL,
	MENU_TYPE_NAME VARCHAR(60) NOT NULL,
	IS_SYS CHAR(1) NOT NULL,
	IS_SYS_DEFAULT CHAR(1) NOT NULL
);
-----菜单项
CREATE TABLE PUB_MENU_ITEM(
	MENU_ID VARCHAR(30) NOT NULL,
	MENU_NAME VARCHAR(60) NOT NULL,
	REQUEST_ACTION VARCHAR(256) NULL,
	TARGET VARCHAR(30) NULL,
	FUNCTION_CODE VARCHAR(30) NULL,
	MODULE_CODE VARCHAR(30) NULL,
	APP_CODE VARCHAR(30) NULL,
	IS_LEAF CHAR(1) NULL
);
----菜单结构
CREATE TABLE PUB_MENU_STRU(
	MENU_STRU_ID VARCHAR(30) NOT NULL,
	MENU_TYPE_ID VARCHAR(10) NOT NULL,
	MENU_ID VARCHAR(30) NOT NULL,
	PARENT_MENU_ID VARCHAR(30) NOT NULL,
	MENU_PATH VARCHAR(600) NULL,
	PATH_NAME VARCHAR(600)  NULL,
	SEQ INT NULL
);
--------------------------------------------角色和角色组-------------------------------------------
------------------角色组----------
CREATE TABLE PUB_ROLE_GROUP(
	ROLE_GROUP_ID VARCHAR(30) NOT NULL,
	ROLE_GROUP_NAME VARCHAR(60) NOT NULL,
	CORPORATION VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(150) NULL
);
-------------角色组应用范围------
CREATE TABLE PUB_ROLE_GROUP_SCOPE(
	ROLE_GROUP_ID VARCHAR(30) NOT NULL,
	SCOPE_VALUE VARCHAR(30) NOT NULL
);
----------角色表--------------------
 CREATE TABLE PUB_ROLES(
 	ROLE_ID VARCHAR(30) NOT NULL,
 	ROLE_NAME VARCHAR(60) NOT NULL,
 	RELATION_ID VARCHAR(30) NULL,
 	ROLE_GROUP_ID VARCHAR(30) NULL,
 	DESCRIPTION VARCHAR(150) NULL
 );
----------角色继承表-----------------
CREATE TABLE PUB_ROLE_PRIVS(
	ROLE_ID VARCHAR(30) NOT NULL,
	GRANTED_ROLE VARCHAR(30) NOT NULL
);
----------不相容角色集表--------------------
CREATE TABLE PUB_CONF_ROLESET(
	SET_ID VARCHAR(30) NOT NULL,
	SET_NAME VARCHAR(30) NULL,
	CARDINALITY INT NULL,
	CORPORATION_ID VARCHAR(30) NULL
);
----------不相容角色表--------------------
CREATE TABLE PUB_CONF_ROLES(
	ROLE_ID VARCHAR(30) NOT NULL,
	SET_ID VARCHAR(30) NOT NULL
);
---------------------------------------------------应用、模块、功能、操作--------------------------------------------------------
---------应用---------
CREATE TABLE PUB_APPS(
 	APP_CODE VARCHAR(30) NOT NULL,
 	APP_NAME VARCHAR(60) NOT NULL,
 	TRANSPORT VARCHAR(10) NULL,
 	SERVER_HOST VARCHAR(30) NULL,
 	PORT VARCHAR(6) NULL,
 	CONTEXT VARCHAR(60) NULL,
 	URI VARCHAR(100) NULL,
 	SEQ INTEGER NULL,
 	NOTE VARCHAR(300) NULL,
 	APP_URL VARCHAR(256) NULL,
 	ICON VARCHAR(256) NULL,
 	TARGET VARCHAR(30) NULL
);
--------模块-----------
CREATE TABLE PUB_MODULES(
 	MODULE_CODE VARCHAR(30) NOT NULL,
 	MODULE_NAME VARCHAR(60) NOT NULL,
 	PARENT_MODULE_CODE VARCHAR(30) NOT NULL,
 	IS_LEAF_MODULE CHAR(1) NOT NULL,
 	APP_CODE VARCHAR(30) NULL,
 	MODULE_PATH VARCHAR(300) NOT NULL,
 	MODULE_PATH_NAME VARCHAR(300) NOT NULL,
 	SEQ INTEGER NOT NULL
);
--------功能-------------
CREATE TABLE PUB_FUNCTIONS(
 	FUNCTION_CODE VARCHAR(30) NOT NULL,
 	FUNCTION_NAME VARCHAR(60) NOT NULL,
 	MODULE_CODE VARCHAR(30) NOT NULL,
 	SEQ INTEGER NOT NULL
);
-------操作--------------
CREATE TABLE PUB_OPERATIONS(
 	OPERATION_CODE VARCHAR(30) NOT NULL,
 	OPERATION_NAME VARCHAR(60) NOT NULL,
 	FUNCTION_CODE VARCHAR(30) NOT NULL,
 	OPERATION_TYPE_CODE VARCHAR(30) NOT NULL,
 	IS_DEFAULT CHAR(1) NOT NULL,
 	SEQ INTEGER NOT NULL
);
----------URL------
CREATE TABLE PUB_URLS(
 	URL_CODE VARCHAR(30) NOT NULL,
 	URL_NAME VARCHAR(60) NOT NULL,
 	URL_CONTENT VARCHAR(500) NOT NULL,
 	OPERATION_CODE VARCHAR(30) NOT NULL,
 	FUNCTION_CODE VARCHAR(30) NOT NULL,
 	ACCESS_TYPE VARCHAR(10) NOT NULL,
 	NOTE VARCHAR(50) NULL,
 	SEQ INTEGER NOT NULL
);
--------------操作类型------------
CREATE TABLE PUB_OPERATION_TYPE(
 	OPERATION_TYPE_CODE VARCHAR(30) NOT NULL,
 	OPERATION_TYPE_NAME VARCHAR(60) NOT NULL
);
--------------------用户角色分配规则-----
CREATE TABLE PUB_USER_ROLE(
 	RULE_ID VARCHAR(30) NOT NULL,
 	RULE_TYPE CHAR(2) NULL,
 	TARGET VARCHAR(30) NOT NULL,
 	ROLE_ID VARCHAR(30) NOT NULL
);

-------角色操作对应
CREATE TABLE PUB_ROLE_OPERATION(
 	ROLE_ID VARCHAR(30) NOT NULL,
 	OPERATION_CODE VARCHAR(30) NOT NULL
);

--创建视图ͼ
------------------用户代理-------------
CREATE TABLE PUB_USER_PROXY(
USER_ID VARCHAR(30) NOT NULL,
PROXY_TYPE CHAR(1) NOT NULL,
PROXY_USER_ID VARCHAR(30) NOT NULL,
PROXY_PERMISSION_ID VARCHAR(30) NULL,
START_TIME CHAR(17) NULL,
END_TIME CHAR(17) NULL
);
--------------代理权限---------------
CREATE TABLE PUB_PROXY_PERMISSION(
  PROXY_PERMISSION_ID VARCHAR(30) NOT NULL,
  PROXY_PERMISSION_NAME VARCHAR(60) NOT NULL,
  PROXY_PERMISSION_CREATOR VARCHAR(30) NOT NULL,
  NOTE VARCHAR(250) NULL
);
-----------------代理权限明细----------------
CREATE TABLE PUB_PROXY_PERMISSION_ITEM(
PROXY_PERMISSION_ITEM_ID  VARCHAR(30) NOT NULL,
ITEM_TYPE VARCHAR(2) NOT NULL,
PROXY_PERMISSION_ITEM_CONTENT VARCHAR(250) NOT NULL,
PROXY_PERMISSION_ID VARCHAR(30) NOT NULL,
NOTE VARCHAR(250) NULL
);

-----------------全局策略-----
CREATE TABLE PUB_GLOBAL_POLICY(
 	PWD_MIN_LENGTH INTEGER NOT NULL,
 	PWD_MAX_LENGTH INTEGER NOT NULL,
 	IS_UPCASE CHAR(1) NOT NULL,
 	IS_LOWERCASE CHAR(1) NOT NULL,
 	IS_NUM CHAR(1) NOT NULL,
 	IS_SPECIALCHAR CHAR(1) NOT NULL,
 	IS_REPEAT CHAR(1) NOT NULL,
 	PWD_LIFE_TIME INTEGER NOT NULL,
 	LOGIN_ATTEMPTS INTEGER NOT NULL,
 	PWD_LOCK_TIME INTEGER NOT NULL,
 	PWD_GRACE_TIME INTEGER NOT NULL
);

---工作日历
CREATE TABLE PUB_ORGAN_WORKDAY
(
            SOLAR_DATE CHAR (8) NOT NULL ,
            ORGAN_ID VARCHAR (30) NOT NULL ,
            LUNAR_DATE CHAR (8) NULL,
            IS_WORKDAY CHAR DEFAULT '1' NOT NULL ,
            WEEK INT NULL,
            NOTE VARCHAR (250) NULL
) ;
CREATE TABLE PUB_FIN_YEAR
(
            ID VARCHAR (30) NOT NULL ,
            ORGAN_ID VARCHAR (30) NOT NULL ,
            FIN_YEAR CHAR (4) NOT NULL ,
            BEGIN_DATE CHAR (8) NOT NULL ,
            END_DATE CHAR (8) NOT NULL ,
            PERIOD_NUM INT NOT NULL 
);
CREATE TABLE PUB_FIN_MONTH
(
            ID VARCHAR (30) NOT NULL ,
            ORGAN_ID VARCHAR (30) NOT NULL ,
            FIN_YEAR CHAR (4) NOT NULL ,
            FIN_MONTH CHAR (6) NOT NULL ,
            BEGIN_DATE CHAR (8) NOT NULL ,
            END_DATE CHAR (8) NOT NULL ,
            SEQ INT NOT NULL ,
            IS_CLOSED CHAR (1) NOT NULL 
);
ALTER TABLE PUB_FIN_YEAR ADD CONSTRAINT PUBFINYEAR_PK PRIMARY KEY (ID);
ALTER TABLE PUB_FIN_MONTH ADD CONSTRAINT PUBFINMONTH_PK PRIMARY KEY (ID);
----创建BSP中的相关主键
----组织结构相关
 ALTER TABLE PUB_ORGAN_WORKDAY
    ADD CONSTRAINT PUBORGANWORKDAY_PK
    PRIMARY KEY (SOLAR_DATE,ORGAN_ID);

 ALTER TABLE PUB_ORGAN_TYPE
    ADD CONSTRAINT PUBORGANTYPE_PK
    PRIMARY KEY (ORGAN_TYPE);

 ALTER TABLE PUB_STRU_TYPE
    ADD CONSTRAINT PUBSTRUTYPE_PK
    PRIMARY KEY (STRU_TYPE);

 ALTER TABLE PUB_STRU_RULE
    ADD CONSTRAINT PUBSTRURULE_PK
    PRIMARY KEY (RULE_ID);

 ALTER TABLE PUB_ORGAN
    ADD CONSTRAINT PUBORGAN_PK
    PRIMARY KEY (ORGAN_ID);

 ALTER TABLE PUB_STRU
    ADD CONSTRAINT PUBSTRU_PK
    PRIMARY KEY (STRU_ID);

 ALTER TABLE PUB_STRU_EXT
    ADD CONSTRAINT PUBSTRUEXT_PK
    PRIMARY KEY (ID);

-----权限相关


-----------------用户---------

ALTER TABLE PUB_USER_TYPE
	ADD CONSTRAINT PUBUSERTYPE_PK
	PRIMARY KEY (USER_TYPE_CODE);

ALTER TABLE PUB_USERS
	ADD CONSTRAINT PUBUSERS_PK
	PRIMARY KEY (USER_ID);

ALTER TABLE PUB_USER_EMPLOYEE
    ADD CONSTRAINT PUBUSEREMPLOYEE_PK
    PRIMARY KEY (USER_ID);

ALTER TABLE PUB_USER_POLICY
	ADD CONSTRAINT PUBUSERPOLICY_PK
	PRIMARY KEY (USER_ID);

--数据类型表
ALTER TABLE PUB_DATA_TYPE ADD CONSTRAINT PUB_DATA_TYPE_PK PRIMARY KEY (DATA_TYPE_CODE);
--组织参数类型表
ALTER TABLE PUB_ORGAN_PARMS_TYPE ADD CONSTRAINT PUB_ORGAN_PARMS_TYPE_PK PRIMARY KEY (ORGAN_PARMS_NAME);

--组织参数表
ALTER TABLE PUB_ORGAN_PARMS ADD CONSTRAINT PUB_ORGAN_PARMS_PK PRIMARY KEY (ORGAN_ID,PARMS_NAME);

--------------------------------------------------------菜单--------------------------------------
--菜单类型主键---
ALTER TABLE PUB_MENU_TYPE
ADD CONSTRAINT PUB_MENU_TYPE_PK
PRIMARY KEY (MENU_TYPE_ID);
--菜单项---
ALTER TABLE PUB_MENU_ITEM
ADD CONSTRAINT PUB_MENU_ITEM_PK
PRIMARY KEY (MENU_ID);
-------菜单结构--
ALTER TABLE PUB_MENU_STRU
ADD CONSTRAINT PUB_MENU_STRU_PK
PRIMARY KEY (MENU_STRU_ID);
------------------------------------------------------角色、角色组-------------------------------------------------
--------角色组------------
ALTER TABLE PUB_ROLE_GROUP
ADD CONSTRAINT PUB_ROLE_GROUP_PK
PRIMARY KEY (ROLE_GROUP_ID);
---------角色组应用范围------
ALTER TABLE PUB_ROLE_GROUP_SCOPE
ADD CONSTRAINT PUB_ROLE_GROUP_SCOPE_PK
PRIMARY KEY (ROLE_GROUP_ID,SCOPE_VALUE);
-----------角色
ALTER TABLE PUB_ROLES
ADD CONSTRAINT PUB_ROLES_PK
PRIMARY KEY (ROLE_ID);
-----------角色继承--------
ALTER TABLE PUB_ROLE_PRIVS
ADD CONSTRAINT PUB_ROLE_PRIVS_PK
PRIMARY KEY (ROLE_ID, GRANTED_ROLE);
-----------不相容角色集--------
ALTER TABLE PUB_CONF_ROLESET
ADD CONSTRAINT PUB_CONF_ROLESET_PK
PRIMARY KEY (SET_ID);
-----------不相容角色--------
ALTER TABLE PUB_CONF_ROLES
ADD CONSTRAINT PUB_CONF_ROLES_PK
PRIMARY KEY (ROLE_ID,SET_ID);
---------------------------------------------------应用、模块、功能、操作--------------------------------------------------------
---------应用---------
ALTER TABLE PUB_APPS
ADD CONSTRAINT PUB_APPS_PK
PRIMARY KEY (APP_CODE);
---------模块-------
ALTER TABLE PUB_MODULES
ADD CONSTRAINT PUB_MODULES_PK
PRIMARY KEY (MODULE_CODE);
---------功能-------
ALTER TABLE PUB_FUNCTIONS
ADD CONSTRAINT PUB_FUNCTIONS_PK
PRIMARY KEY (FUNCTION_CODE);
---------操作-------
ALTER TABLE PUB_OPERATIONS
ADD CONSTRAINT PUB_OPERATIONS_PK
PRIMARY KEY (OPERATION_CODE);
---------操作URL-------
ALTER TABLE PUB_URLS
ADD CONSTRAINT PUB_URLS_PK
PRIMARY KEY (URL_CODE);
---------操作类型-------
ALTER TABLE PUB_OPERATION_TYPE
ADD CONSTRAINT PUB_OPERATION_TYPE_PK
PRIMARY KEY (OPERATION_TYPE_CODE);
--------------------用户角色分配规则-----
ALTER TABLE PUB_USER_ROLE
ADD CONSTRAINT PUB_USER_ROLE_PK
PRIMARY KEY (RULE_ID);
--------------------角色操作对应-----
ALTER TABLE PUB_ROLE_OPERATION
ADD CONSTRAINT PUB_ROLE_OPERATION_PK
PRIMARY KEY (ROLE_ID,OPERATION_CODE);

-----------------权限代理
ALTER TABLE PUB_USER_PROXY
   ADD CONSTRAINT  PUBUSERPROXY_PK
       PRIMARY KEY(USER_ID,PROXY_USER_ID,PROXY_TYPE);

ALTER TABLE PUB_PROXY_PERMISSION
   ADD CONSTRAINT PROXYPREMISSION_PK
     PRIMARY KEY(PROXY_PERMISSION_ID);

ALTER TABLE PUB_PROXY_PERMISSION_ITEM
    ADD CONSTRAINT PROXYPREMISSIONITEM_PK
      PRIMARY KEY(PROXY_PERMISSION_ITEM_ID);
----###################################创建BSP中的相关外键的SQL##################------------

---组织结构相关
ALTER TABLE PUB_ORGAN
    ADD CONSTRAINT PUBORGAN_FK1 FOREIGN KEY (ORGAN_TYPE)
    REFERENCES PUB_ORGAN_TYPE (ORGAN_TYPE);

ALTER TABLE PUB_STRU_RULE
    ADD CONSTRAINT PUBSTRURULE_FK1 FOREIGN KEY (SRC_REF)
    REFERENCES PUB_ORGAN_TYPE (ORGAN_TYPE);

ALTER TABLE PUB_STRU_RULE
    ADD CONSTRAINT PUBSTRURULE_FK2 FOREIGN KEY (TARGET_REF)
    REFERENCES PUB_ORGAN_TYPE (ORGAN_TYPE);

ALTER TABLE PUB_STRU_RULE
    ADD CONSTRAINT PUBSTRURULE_FK3 FOREIGN KEY (STRU_TYPE)
    REFERENCES PUB_STRU_TYPE (STRU_TYPE);

ALTER TABLE PUB_STRU
    ADD CONSTRAINT PUBSTRU_FK1 FOREIGN KEY (ORGAN_ID)
    REFERENCES PUB_ORGAN (ORGAN_ID);

ALTER TABLE PUB_STRU
    ADD CONSTRAINT PUBSTRU_FK2 FOREIGN KEY (STRU_TYPE)
    REFERENCES PUB_STRU_TYPE (STRU_TYPE);

ALTER TABLE PUB_STRU_EXT
    ADD CONSTRAINT PUBSTRUEXT_FK1 FOREIGN KEY (SRC_ID)
    REFERENCES PUB_ORGAN (ORGAN_ID);

ALTER TABLE PUB_STRU_EXT
    ADD CONSTRAINT PUBSTRUEXT_FK2 FOREIGN KEY (TARGET_ID)
    REFERENCES PUB_ORGAN (ORGAN_ID);

ALTER TABLE PUB_STRU_EXT
    ADD CONSTRAINT PUBSTRUEXT_FK3 FOREIGN KEY (STRU_TYPE)
    REFERENCES PUB_STRU_TYPE (STRU_TYPE);

ALTER TABLE PUB_STRU_EXT
    ADD CONSTRAINT PUBSTRUEXT_FK4 FOREIGN KEY (STRU_ID)
    REFERENCES PUB_STRU (STRU_ID);


----权限相关

--------------------------------------------------------菜单--------------------------------------
--菜单结构---
ALTER TABLE PUB_MENU_STRU
    ADD CONSTRAINT PUB_MENU_STRU_FK1 FOREIGN KEY (MENU_TYPE_ID)
    REFERENCES PUB_MENU_TYPE(MENU_TYPE_ID);
ALTER TABLE PUB_MENU_STRU
    ADD CONSTRAINT PUB_MENU_STRU_FK2 FOREIGN KEY (MENU_ID)
    REFERENCES PUB_MENU_ITEM(MENU_ID);
---------------------------------------------------应用、模块、功能、操作--------------------------------------------------------
--------模块--------
ALTER TABLE PUB_MODULES
ADD CONSTRAINT PUB_MODULES_FK1 FOREIGN KEY (APP_CODE)
REFERENCES PUB_APPS(APP_CODE);
--------功能--------
ALTER TABLE PUB_FUNCTIONS
ADD CONSTRAINT PUB_FUNCTIONS_FK1 FOREIGN KEY (MODULE_CODE)
REFERENCES PUB_MODULES(MODULE_CODE);
--------操作--------
ALTER TABLE PUB_OPERATIONS
ADD CONSTRAINT PUB_OPERATIONS_FK1 FOREIGN KEY (FUNCTION_CODE)
REFERENCES PUB_FUNCTIONS(FUNCTION_CODE);

ALTER TABLE PUB_OPERATIONS
ADD CONSTRAINT PUB_OPERATIONS_FK2 FOREIGN KEY (OPERATION_TYPE_CODE)
REFERENCES PUB_OPERATION_TYPE(OPERATION_TYPE_CODE);
--------操作URL--------
ALTER TABLE PUB_URLS
ADD CONSTRAINT PUB_URLS_FK1 FOREIGN KEY (OPERATION_CODE)
REFERENCES PUB_OPERATIONS(OPERATION_CODE);

ALTER TABLE PUB_URLS
ADD CONSTRAINT PUB_URLS_FK2 FOREIGN KEY (FUNCTION_CODE)
REFERENCES PUB_FUNCTIONS(FUNCTION_CODE);
----------角色继承------
ALTER TABLE PUB_ROLE_PRIVS
ADD CONSTRAINT PUB_ROLE_PRIVS_FK1 FOREIGN KEY (GRANTED_ROLE)
REFERENCES PUB_ROLES(ROLE_ID);
----------不相容角色------
ALTER TABLE PUB_CONF_ROLES
ADD CONSTRAINT PUB_CONF_ROLES_FK1 FOREIGN KEY (ROLE_ID)
REFERENCES PUB_ROLES(ROLE_ID);

ALTER TABLE PUB_CONF_ROLES
ADD CONSTRAINT PUB_CONF_ROLES_FK2 FOREIGN KEY (SET_ID)
REFERENCES PUB_CONF_ROLESET(SET_ID);
--------------------用户角色分配规则-----
ALTER TABLE PUB_USER_ROLE
ADD CONSTRAINT PUB_USER_ROLE_FK1 FOREIGN KEY (ROLE_ID)
REFERENCES PUB_ROLES(ROLE_ID);
--------------角色操作对应-------
ALTER TABLE PUB_ROLE_OPERATION
ADD CONSTRAINT PUB_ROLE_OPERATION_FK1 FOREIGN KEY (OPERATION_CODE)
REFERENCES PUB_OPERATIONS(OPERATION_CODE);
ALTER TABLE PUB_ROLE_OPERATION
ADD CONSTRAINT PUB_ROLE_OPERATION_FK2 FOREIGN KEY (ROLE_ID)
REFERENCES PUB_ROLES(ROLE_ID);

--------------------权限代理---------
ALTER TABLE PUB_USER_PROXY
    ADD CONSTRAINT USERPROXY_FK1 FOREIGN KEY (USER_ID)
    REFERENCES PUB_USERS (USER_ID);

ALTER TABLE PUB_USER_PROXY
    ADD CONSTRAINT USERPROXY_FK2 FOREIGN KEY (PROXY_USER_ID)
    REFERENCES PUB_USERS (USER_ID);

ALTER TABLE PUB_PROXY_PERMISSION_ITEM
    ADD CONSTRAINT PROXYPERMITEM_FK1 FOREIGN KEY (PROXY_PERMISSION_ID)
    REFERENCES PUB_PROXY_PERMISSION (PROXY_PERMISSION_ID);
----创建BSP中的相关索引
----20100622 添加数据字典模块-------
CREATE TABLE PUB_DICT (
      DICT_CODE VARCHAR(32) NOT NULL ,
      DICT_NAME VARCHAR(60) NOT NULL,
      SET_MAN VARCHAR(30),
      SET_TIME VARCHAR(17),
      NOTE  VARCHAR(100),
      IN_USE CHAR(1)
);

CREATE TABLE PUB_DICT_ITEM(
     ITEM_CODE VARCHAR(32) NOT NULL,
     DICT_CODE VARCHAR(32) NOT NULL,
     ITEM_VALUE VARCHAR(100) NOT NULL,
     XH INT,
     PARENT_CODE VARCHAR(32),
     NOTE VARCHAR(100),
     IN_USE CHAR (1) DEFAULT '1' NOT NULL
);
ALTER TABLE PUB_DICT
  ADD CONSTRAINT PUB_DICT_PK PRIMARY KEY (DICT_CODE);

ALTER TABLE PUB_DICT_ITEM
  ADD CONSTRAINT PUB_DICT_ITEM_PK PRIMARY KEY (DICT_CODE, ITEM_CODE);
--20100906创建收藏菜单
CREATE TABLE PUB_COLLECTMENU(
	            MENU_ID VARCHAR(30)  NOT NULL ,
	            USER_ID VARCHAR (30) NOT NULL ,
	            NAME VARCHAR (50) ,
	            ALIAS VARCHAR(50),
	            PARENT_ID  VARCHAR (30),
	            URL VARCHAR (500) ,
	            TARGET VARCHAR (10),
		        MENU_ORDER INT
	);
ALTER TABLE PUB_COLLECTMENU ADD CONSTRAINT PUB_COLLECTMENU_PK PRIMARY KEY (MENU_ID, USER_ID);

--20100913用户映射
CREATE TABLE PUB_USER_MAP
(
            USER_ID VARCHAR (250) NOT NULL ,
            MAP_VALUE VARCHAR (250) NOT NULL,
			TYPE_ID CHAR(2) NOT NULL
);
 ALTER TABLE PUB_USER_MAP
    ADD CONSTRAINT PubUserMap_PK 
	PRIMARY KEY (USER_ID,TYPE_ID);

--20100926LDAP用户同步
CREATE TABLE PUB_LDAP_SYN_USERS ( 
	USER_ID VARCHAR(32) NOT NULL,
	USER_NAME VARCHAR(32),
	PASSWORD VARCHAR(30),
	MOBILE VARCHAR(30),
	EMAIL VARCHAR(30)
)
;
ALTER TABLE PUB_LDAP_SYN_USERS ADD CONSTRAINT PUBLDAPSYNUSERS_PK 
	PRIMARY KEY (USER_ID);