--页面 
CREATE TABLE CP_PAGE
(
  ID VARCHAR (32) NOT NULL,
  NAME VARCHAR (100),
  DESCRIPTION VARCHAR (100),
  IS_RELEASE CHAR (1) NOT NULL,
  CONTENT TEXT,
  CREATE_TIME CHAR (17) NOT NULL,
  UPDATE_TIME CHAR (17) NOT NULL,
  ICON VARCHAR (255)
);
ALTER TABLE CP_PAGE
    ADD CONSTRAINT CP_PAGE_PK
PRIMARY KEY (ID);

--页面微件
CREATE TABLE CP_PAGE_WIDGET
(
  ID VARCHAR (32) NOT NULL,
  PAGE_ID VARCHAR (32) NOT NULL,
  WIDGET_ID VARCHAR (1024) NOT NULL
);
ALTER TABLE CP_PAGE_WIDGET
    ADD CONSTRAINT CP_PW_PK
PRIMARY KEY (ID);

--微件类别
CREATE TABLE CP_WIDGET_TYPE
(
  ID VARCHAR (32) NOT NULL,
  NAME VARCHAR (100),
  DESCRIPTION VARCHAR (100),
  DISPLAY_ORDER INT,
  PARENT_ID VARCHAR (32) NOT NULL
);
ALTER TABLE CP_WIDGET_TYPE
    ADD CONSTRAINT CP_WT_PK
PRIMARY KEY (ID);

--微件
CREATE TABLE CP_WIDGET
(
  ID VARCHAR (32) NOT NULL,
  NAME VARCHAR (100),
  DESCRIPTION VARCHAR (100),
  CONTENT VARCHAR (255) NOT NULL,
  AUTHOR VARCHAR(32) NOT NULL,
  ICON  VARCHAR (255) NOT NULL,
  HEIGHT INT,
  LOAD_TYPE CHAR(1),
  DISPLAY_ORDER INT,
  TYPE_ID VARCHAR (32) NOT NULL,
  CREATE_TIME CHAR (17) NOT NULL,
  UPDATE_TIME CHAR (17) NOT NULL,
  EXPAND_CONTENT VARCHAR (255)
);
ALTER TABLE CP_WIDGET
    ADD CONSTRAINT CP_WIDGET_PK
PRIMARY KEY (ID);
--用户页面微件
CREATE TABLE CP_PAGE_WIDGET_USER
(
  ID VARCHAR (32) NOT NULL,
  PAGE_ID VARCHAR (32) NOT NULL,
  WIDGET_ID VARCHAR (1024) NOT NULL,
  USER_ID VARCHAR (32) NOT NULL
);
ALTER TABLE CP_PAGE_WIDGET_USER
    ADD CONSTRAINT CP_PWU_PK
PRIMARY KEY (ID);
