--角色
INSERT INTO PUB_ROLES(ROLE_ID,ROLE_NAME,RELATION_ID,ROLE_GROUP_ID,DESCRIPTION) VALUES('CPORTALADMIN','CPortal Administrator','1',NULL,'CPortal Administrator');

--CPORTALADMIN功能权限
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('CPORTALADMIN', 'CPORTAL01000');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('CPORTALADMIN', 'CPORTAL01001');

--SUPERADMIN功能权限
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('SUPERADMIN', 'CPORTAL01000');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES ('SUPERADMIN', 'CPORTAL01001');