#############################PUB_ROLES 角色#############################

INSERT INTO PUB_ROLES(ROLE_ID,ROLE_NAME,RELATION_ID,ROLE_GROUP_ID,DESCRIPTION) VALUES('WORKFLOWADMIN','工作流管理员','1',NULL,NULL);
INSERT INTO PUB_ROLES(ROLE_ID,ROLE_NAME,RELATION_ID,ROLE_GROUP_ID,DESCRIPTION) VALUES('WORKFLOWCOMUSER','工作流普通人员','1',NULL,NULL);

#########################PUB_ROLE_RESOURCE 角色资源对应##################
######工作流管理员具有表单定义、流程定义、管理监控、
###工作流普通人员具有任务列表、流转状态



###
### Table: PUB_ROLE_OPERATION
###

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW01000');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW01001');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW01002');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW01003');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW01010');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW01011');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_TASKLIST_DEFAULT_DBQ');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_TASK_LIST_DEFAULT_EQ');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_TASK_LIST_DEFAULT_NN');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_TASK_LIST_DEFAULT_YBQ');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_CONFIG_PROCDEF');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_PROCESS_RESUME_EVENT');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_PROC_PERMISSION_CONF');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_FORM_MGR_JSP_DEF');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_FORM_MGR_JSP_DEL');
    
-- workflowcustomer
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWCOMUSER', 'WORKFLOW_TASKLIST_DEFAULT_DBQ');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWCOMUSER', 'WORKFLOW_TASK_LIST_DEFAULT_EQ');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWCOMUSER', 'WORKFLOW_TASK_LIST_DEFAULT_NN');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWCOMUSER', 'WORKFLOW_TASK_LIST_DEFAULT_YBQ');
   
##为superadmin赋工作流管理员的权限
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW01000');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW01001');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW01002');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW01003');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW01010');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW01011');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_TASKLIST_DEFAULT_DBQ');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_TASK_LIST_DEFAULT_EQ');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_TASK_LIST_DEFAULT_NN');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_TASK_LIST_DEFAULT_YBQ');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_CONFIG_PROCDEF');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_PROCESS_RESUME_EVENT');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES
    ('SUPERADMIN', 'WORKFLOW_PROC_PERMISSION_CONF');
    
 
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_FORM_MGR_JSP_DEF');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_FORM_MGR_JSP_DEL');
    
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_PLUGIN_REGISTER');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWCOMUSER', 'WORKFLOW_PLUGIN_REGISTER');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_PLUGIN_REGISTER');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('WORKFLOWADMIN', 'WORKFLOW_PARTICIPANT_CONFIG');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
    ('SUPERADMIN', 'WORKFLOW_PARTICIPANT_CONFIG');
    
##流程统计分析
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES
	('WORKFLOWADMIN', 'WORKFLOW_ALL_PROCESS_ANALYSIS');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES
	('WORKFLOWADMIN', 'WORKFLOW_ALL_PART_ANALYSIS');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES
	('SUPERADMIN', 'WORKFLOW_ALL_PROCESS_ANALYSIS');
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES
	('SUPERADMIN', 'WORKFLOW_ALL_PART_ANALYSIS');
	
## BPMN
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID,OPERATION_CODE) VALUES 
	('WORKFLOWADMIN','WF_BPMN_PROCESS_DESIGN_QUERY');
	
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID,OPERATION_CODE) VALUES 
	('WORKFLOWCOMUSER','WF_BPMN_PROCESS_DESIGN_QUERY');
	
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID,OPERATION_CODE) VALUES 
	('SUPERADMIN','WF_BPMN_PROCESS_DESIGN_QUERY');	
